### PR TITLE
Teacher teach - transfer class to another teacher

### PR DESCRIPTION
**Pull request by cewei8483**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/181)

### CODE REVIEW

**Review by KamilPawel — CHANGES_REQUESTED** [review]
seems you did not merge dev ? the getStudents endpoint for the table of students is not being displayed 

> Reviewed 9 of 15 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/181#-:-Nfz1le_47FjCjfXW5zT:b-jnmhwv)* status: 12 of 16 files reviewed, 1 unresolved discussion (waiting on @cewei8483)

___
*[`backend/portal/views/teacher/teach.py` line 349 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/181#-Nfz-Sh6Ee28P1UruuuP:-Nfz-Sh6Ee28P1UruuuQ:b2id5b6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/00e3dc8d42a2317e559ac3e021de3350dedee52a/backend/portal/views/teacher/teach.py#L349)):*
> ```Python
>                     request, klass, blockly_episodes, python_episodes
>                 )
>         # elif "class_move_submit" in request.POST:
> ```

If not used plz remove

**Review by KamilPawel — APPROVED** [review]
:lgtm:

> Reviewed 3 of 15 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/181#-:-NfzE-Du27R8nM5_Hf7R:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @cewei8483)

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/181)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[`backend/portal/views/teacher/teach.py` line 349 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/181#-Nfz-Sh6Ee28P1UruuuP:-NfzGoNU1SqFr4jpG1cy:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/00e3dc8d42a2317e559ac3e021de3350dedee52a/backend/portal/views/teacher/teach.py#L349)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

If not used plz remove
</blockquote></details>

Done.

**Review by KamilPawel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/181#-:-NfzHlcW1vw-gUnnqVmb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Pull request merged**
