### PR TITLE
reset students' password

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`backend/Pipfile` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306#-Nr5d1qH3MSL9q_mTqRB:-Nr5d1qH3MSL9q_mTqRC:b-yr295e) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/891e2da6be2a7284fa8eb8b1577697a3911c5633/backend/Pipfile#L10)):*
> ```TOML
> #   https://github.com/ocadotechnology/codeforlife-package-python/blob/{ref}/Pipfile
> # Replace "{ref}" in the above URL with the ref set below.
> codeforlife = {ref = "reset_students_password", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> ```

Update
___
*[`backend/api/tests/views/test_user.py` line 310 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306#-Nr5e0Hi18iPh7PrlAP8:-Nr5e0Hi18iPh7PrlAP9:b-934goq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/891e2da6be2a7284fa8eb8b1577697a3911c5633/backend/api/tests/views/test_user.py#L310)):*
> ```Python
>         response = self.client.patch(
>             self.reverse_action("students--reset-password"),
>             [student_user.id for student_user in student_users],
> ```

Do we want to make it so that the test excludes some students, so we can assert that these students' passwords and login IDs don't get reset?
___
*[`backend/api/tests/views/test_user.py` line 333 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306#-Nr5ekQbClBsLsjT3kAE:-Nr5ekQbClBsLsjT3kAF:b6dtbud) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/891e2da6be2a7284fa8eb8b1577697a3911c5633/backend/api/tests/views/test_user.py#L333)):*
> ```Python
> 
>             student_user.refresh_from_db()
>             assert student_user.check_password(password)
> ```

Can you assert the student can login too

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306)* status: all files reviewed, 4 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/views/user.py` line 156 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306#-Nr5utCc-nEMhYJqezq3:-Nr5utCc-nEMhYJqezq4:b-7n0o2d) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/891e2da6be2a7284fa8eb8b1577697a3911c5633/backend/api/views/user.py#L156)):*
> ```Python
>         fields: t.Dict[int, DataDict] = {}
>         for pk in queryset.values_list("pk", flat=True):
>             student_user = StudentUser(pk=pk)
> ```

Do we need validation here in case the Students don't exist?

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306)* status: 8 of 14 files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`backend/Pipfile` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306#-Nr5d1qH3MSL9q_mTqRB:-Nr60i-j0MCFhMaQhpO4:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/891e2da6be2a7284fa8eb8b1577697a3911c5633/backend/Pipfile#L10)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Update
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 310 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306#-Nr5e0Hi18iPh7PrlAP8:-Nr60zmL3pozgWcNNJOn:bw3vopn) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/891e2da6be2a7284fa8eb8b1577697a3911c5633/backend/api/tests/views/test_user.py#L310)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we want to make it so that the test excludes some students, so we can assert that these students' passwords and login IDs don't get reset?
</blockquote></details>

I don't think that's necessary because that would be testing the queryset and we already have separate tests for the queryset 
___
*[`backend/api/tests/views/test_user.py` line 333 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306#-Nr5ekQbClBsLsjT3kAE:-Nr6Q_ZHAlf9Of_xDTPO:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/891e2da6be2a7284fa8eb8b1577697a3911c5633/backend/api/tests/views/test_user.py#L333)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Can you assert the student can login too
</blockquote></details>

Done.
___
*[`backend/api/views/user.py` line 156 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306#-Nr5utCc-nEMhYJqezq3:-Nr6-eBr54CZIPNaG_hh:b-h01tsh) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/891e2da6be2a7284fa8eb8b1577697a3911c5633/backend/api/views/user.py#L156)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we need validation here in case the Students don't exist?
</blockquote></details>

no because then the queryset will just be empty and the for-loop won't iterate.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`backend/api/views/user.py` line 60 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306#-Nr6Qf45AFkWKSrsy2Lz:-Nr6Qf45AFkWKSrsy2M-:byp18fd) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6fdcdd59428b4327e825a225de1a5a4f0977bbde/backend/api/views/user.py#L60)):*
> ```Python
> 
>     # def destroy(self, request: Request):
>     #     return super().des
> ```

Remove

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/306#-:-Nr6R4n1AjnbGbYVPZPX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
