### PR TITLE
Bulk create students

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259)* status: 0 of 11 files reviewed, 2 unresolved discussions

___
*[`backend/api/serializers/user.py` line 21 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpPcoh9AmWmp-SGMTJO:-NpPcoh9AmWmp-SGMTJP:berr8u3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e023b4017a66845f6078d417c712a91bd04b4dbe/backend/api/serializers/user.py#L21)):*
> ```Python
> 
> # pylint: disable-next=missing-class-docstring
> class UserListSerializer(ModelListSerializer[User]):
> ```

validate that student first names are unique per class.
___
*[`backend/api/serializers/user.py` line 44 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpPfjPg3uCb6aPZ2Ztu:-NpPfjPg3uCb6aPZ2Ztv:b-ey9pxx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e023b4017a66845f6078d417c712a91bd04b4dbe/backend/api/serializers/user.py#L44)):*
> ```Python
>             user = User.objects.create_user(
>                 first_name=user_fields["first_name"],
>                 # last_name="",
> ```

remove comments

**Comment by SKairinos** [comment]
*[`backend/api/serializers/student.py` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpPhCU-8cwBddf0SZLZ:-NpPhCU-8cwBddf0SZL_:bx8b7p8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e023b4017a66845f6078d417c712a91bd04b4dbe/backend/api/serializers/student.py#L19)):*
> ```Python
> 
>     # pylint: disable-next=missing-function-docstring
>     def validate_klass(self, value: str):
> ```

validate is admin teacher or in same class

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259)* status: 0 of 11 files reviewed, all discussions resolved

___
*[`backend/api/serializers/student.py` line 19 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpPhCU-8cwBddf0SZLZ:-NpPrMX06lrAYmAx9rG0:bb6un1j) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e023b4017a66845f6078d417c712a91bd04b4dbe/backend/api/serializers/student.py#L19)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

validate is admin teacher or in same class
</blockquote></details>

Done
___
*[`backend/api/serializers/user.py` line 21 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpPcoh9AmWmp-SGMTJO:-NpQ2zmO-Y77cc6T0ct4:bb6un1j) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e023b4017a66845f6078d417c712a91bd04b4dbe/backend/api/serializers/user.py#L21)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

validate that student first names are unique per class.
</blockquote></details>

Done

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259)* status: all files reviewed, 9 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/serializers/student.py` line 32 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQImtt4srR6ZlhKy78:-NpQImtt4srR6ZlhKy79:b-ol5rpi) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/student.py#L32)):*
> ```Python
>         if not queryset.filter(
>             teacher__school=self.request_user.teacher.school_id,
>         ).exists():
> ```

Could we simplify this by saying:

`klass = Class.objects.get(access_code=value)
if klass.teacher.school != teacher.school:`

?

Which actually brings up 2 follow up questions:

1. Is there a reason you're using `filter` here instead of `get`?
2. Do we need to add a validation in case the class in question doesn't exist, or is this already handled somewhere else?
___
*[`backend/api/serializers/student.py` line 39 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQJsJh2Zf-XXycXkJA:-NpQJsJh2Zf-XXycXkJB:b-uy7x76) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/student.py#L39)):*
> ```Python
>             not self.request_user.teacher.is_admin
>             and not queryset.filter(teacher=self.request_user.teacher).exists()
>         ):
> ```

Assuming you've already collected `klass` earlier, could we do:

`if not teacher.is_admin and klass.teacher != teacher:`

OR

`if not (teacher.is_admin or klass.teacher == teacher):



_Suggestion:_
```Python
        if (
            not teacher.is_admin
            and not queryset.filter(teacher=teacher).exists()
        ):
```
___
*[`backend/api/serializers/student.py` line 36 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQLjvH781CQPgWmC3f:-NpQLjvH781CQPgWmC3g:b-1pi4nd) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d567ac2b641cc53f710e7fc81906c32b0d446759/backend/api/serializers/student.py#L36)):*
> ```Python
>             )
>         if (
>             not teacher.is_admin
> ```

sanity check: it's OK to check admin status here WITHOUT checking they belong to the school because that check already happened earlier in this file, correct? (just want to make sure we don't give admin teachers the ability to manipulate any school's data).
___
*[`backend/api/serializers/user.py` line 53 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQNJD-08dePbnXQJyp:-NpQNJD-08dePbnXQJyq:b-48q02m) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/user.py#L53)):*
> ```Python
>             user._password = password
> 
>             # TODO: Is this needed?
> ```

You had a question about this that you didn't bring up in the end.
This seems to be for generating the student's direct login link, so yes I imagine this is still needed.
___
*[`backend/api/serializers/user.py` line 95 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQODaI6SvXhcWsdynN:-NpQODaI6SvXhcWsdynO:be2bk4s) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/user.py#L95)):*
> ```Python
>                 )
> 
>             # Validate first name is not specified more than once in data.
> ```

Not sure, but would it make more sense to perform this check first, before even checking for duplicate entries with the class data? Not sure if it makes a massive difference to be honest since they'll both stop the other one from running.
___
*[`backend/api/serializers/user.py` line 110 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQOmHrACkvnmRTbjWj:-NpQOmHsC7xgzSmMDc8I:b-f6amn6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/user.py#L110)):*
> ```Python
> class UserSerializer(_UserSerializer):
>     student = StudentSerializer(source="new_student", required=False)
> ```

This new line here irks me but it's purely a preference so up to you if you want to remove it or not
___
*[`backend/api/serializers/user.py` line 112 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQOtDaEOtqk38Lv9r9:-NpQOtDaEOtqk38Lv9rA:b-v4k3t5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/user.py#L112)):*
> ```Python
> 
>     teacher = TeacherSerializer(source="new_teacher", required=False)
> ```

Same thing with this one
___
*[`backend/api/tests/signals/test_user.py` line 28 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQMH7m7QTi9MyQJQrf:-NpQMH7m7QTi9MyQJQrg:bc0xx69) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/tests/signals/test_user.py#L28)):*
> ```Python
>         """
> 
>         user = User.objects.filter(new_teacher__id__isnull=False).first()
> ```

Could we just do `filter(new_teacher__isnull=False)`, or do we need to check on the `id`?
___
*[`backend/api/tests/views/test_user.py` line 54 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQMbXkEvcLsXcAcgmk:-NpQMbXkEvcLsXcAcgml:b8ag70r) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/tests/views/test_user.py#L54)):*
> ```Python
>         self.assertTrue(response.json())
> 
>     def test_bulk_create__students(self):
> ```

Do we want to add to this so we capture the various validation errors that the serializer could throw?

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259)* status: 8 of 11 files reviewed, 9 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/serializers/student.py` line 32 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQImtt4srR6ZlhKy78:-NpQQAwt8-RFb0G_5Iug:b-7w0ehv) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/student.py#L32)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Could we simplify this by saying:

`klass = Class.objects.get(access_code=value)
if klass.teacher.school != teacher.school:`

?

Which actually brings up 2 follow up questions:

1. Is there a reason you're using `filter` here instead of `get`?
2. Do we need to add a validation in case the class in question doesn't exist, or is this already handled somewhere else?
</blockquote></details>

You are right on both accounts:
1. It's either or. I would only prefer `filter()` over `get()` if I didn't want to retrieve the data and just simply wanted to check if it `exists()`. In this case, I do want to get the data.
2. Yes. Added now with `get()`. I have to do this because technically access_code is not a key.
___
*[`backend/api/serializers/student.py` line 39 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQJsJh2Zf-XXycXkJA:-NpQS3k83KQUlsq82AiK:b-6hp4gj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/student.py#L39)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Assuming you've already collected `klass` earlier, could we do:

`if not teacher.is_admin and klass.teacher != teacher:`

OR

`if not (teacher.is_admin or klass.teacher == teacher):
</blockquote></details>

yes, you're right. Done.
___
*[`backend/api/serializers/student.py` line 36 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQLjvH781CQPgWmC3f:-NpQRlzYAHkG3dfkwVLr:b-5dxttw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d567ac2b641cc53f710e7fc81906c32b0d446759/backend/api/serializers/student.py#L36)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

sanity check: it's OK to check admin status here WITHOUT checking they belong to the school because that check already happened earlier in this file, correct? (just want to make sure we don't give admin teachers the ability to manipulate any school's data).
</blockquote></details>

yes, exactly. this check only runs after we've confirmed the requesting teacher is in the same school as the class. 
___
*[`backend/api/serializers/user.py` line 53 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQNJD-08dePbnXQJyp:-NpQTFCk2WpntmVcs3vk:brety6s) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/user.py#L53)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You had a question about this that you didn't bring up in the end.
This seems to be for generating the student's direct login link, so yes I imagine this is still needed.
</blockquote></details>

let's have a call about this.
___
*[`backend/api/serializers/user.py` line 95 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQODaI6SvXhcWsdynN:-NpQUMMs9WrdAL3JcW4E:bc7as61) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/user.py#L95)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Not sure, but would it make more sense to perform this check first, before even checking for duplicate entries with the class data? Not sure if it makes a massive difference to be honest since they'll both stop the other one from running.
</blockquote></details>

yes, you are right. we should check that the local data is valid first before opening a db connection and checking the remote data. more efficient.
___
*[`backend/api/serializers/user.py` line 110 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQOmHrACkvnmRTbjWj:-NpQUb006Bo_dUJK3aTp:bh8012o) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/user.py#L110)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This new line here irks me but it's purely a preference so up to you if you want to remove it or not
</blockquote></details>

haha. The convention I've been following is we have one new line between all model/serilaizer fields to allow the code to breathe. Like this:
https://github.com/ocadotechnology/codeforlife-package-python/blob/1c9ac1dafadee4e51291e039ccdb9097876252df/codeforlife/user/models/user.py#L116
What do you think?
___
*[`backend/api/serializers/user.py` line 112 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQOtDaEOtqk38Lv9r9:-NpQUtUZ2Ayr9xAu8byZ:byr4ffv) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/user.py#L112)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same thing with this one
</blockquote></details>

see above
___
*[`backend/api/tests/signals/test_user.py` line 28 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQMH7m7QTi9MyQJQrf:-NpQVFrF1sj7MYiYWeru:b-4v41re) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/tests/signals/test_user.py#L28)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Could we just do `filter(new_teacher__isnull=False)`, or do we need to check on the `id`?
</blockquote></details>

you are right. fixed.
___
*[`backend/api/tests/views/test_user.py` line 54 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQMbXkEvcLsXcAcgmk:-NpQVL_p65RMcGr2vSGs:b-cdkwex) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/tests/views/test_user.py#L54)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we want to add to this so we capture the various validation errors that the serializer could throw?
</blockquote></details>

good question! let's discuss on a call as part  of our test strategy.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/serializers/user.py` line 53 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQNJD-08dePbnXQJyp:-NpQYxHx9gmbo5_lehf9:b225vdp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/user.py#L53)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

let's have a call about this.
</blockquote></details>

Remove TODO
___
*[`backend/api/serializers/user.py` line 110 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQOmHrACkvnmRTbjWj:-NpQZA0j0CNFwAW3Z__7:bt62m55) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/user.py#L110)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

haha. The convention I've been following is we have one new line between all model/serilaizer fields to allow the code to breathe. Like this:
https://github.com/ocadotechnology/codeforlife-package-python/blob/1c9ac1dafadee4e51291e039ccdb9097876252df/codeforlife/user/models/user.py#L116
What do you think?
</blockquote></details>

Ah that's interesting, lol. I feel like it makes sense to have a new line in between the fields in your example here because they are defined on multiple lines already.
But if the field definition fits on 1 line then I don't like having a new line after it.

Maybe too finicky though. Whatever you feel is easiest to follow.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/tests/views/test_user.py` line 54 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQMbXkEvcLsXcAcgmk:-NpQaYfhBXHDC3tIkL8U:b-9efomm) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/tests/views/test_user.py#L54)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

good question! let's discuss on a call as part  of our test strategy.
</blockquote></details>

Add tests pls sozzles

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259)* status: all files reviewed, 5 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/tests/serializers/test_student.py` line 39 at r5](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpVQn3y3kkLWr2Ld5SJ:-NpVQn3y3kkLWr2Ld5SK:bipkkx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/5404604c90912545ec6078d349dd92fce18c6239/backend/api/tests/serializers/test_student.py#L39)):*
> ```Python
>     def test_validate_klass__does_not_exist(self):
>         """
>         Requesting teacher cannot assign a student to a call that doesn't exist.
> ```

"to a class"
___
*[`backend/api/tests/serializers/test_student.py` line 64 at r5](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpVRd6V6NFoX2lYv5qg:-NpVRd6V6NFoX2lYv5qh:b-9mfj2l) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/5404604c90912545ec6078d349dd92fce18c6239/backend/api/tests/serializers/test_student.py#L64)):*
> ```Python
>             teacher__school=user.teacher.school
>         ).first()
>         assert klass is not None
> ```

assert klass has different school to teacher's
___
*[`backend/api/tests/serializers/test_student.py` line 89 at r5](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpVRiiE7bRc6yjV8Etm:-NpVRiiE7bRc6yjV8Etn:b-djy8pd) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/5404604c90912545ec6078d349dd92fce18c6239/backend/api/tests/serializers/test_student.py#L89)):*
> ```Python
>             .first()
>         )
>         assert klass is not None
> ```

assert klass teacher isn't request teacher

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259)* status: all files reviewed, 5 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/serializers/user.py` line 53 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQNJD-08dePbnXQJyp:-NpVZH0L4ANLWvji9dd_:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/user.py#L53)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove TODO
</blockquote></details>

Done.
___
*[`backend/api/serializers/user.py` line 110 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpQOmHrACkvnmRTbjWj:-NpVZe_J0sftplzFZiz_:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/3e067676c8bee501d8b1b04aeb15999d7847d7b2/backend/api/serializers/user.py#L110)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Ah that's interesting, lol. I feel like it makes sense to have a new line in between the fields in your example here because they are defined on multiple lines already.
But if the field definition fits on 1 line then I don't like having a new line after it.

Maybe too finicky though. Whatever you feel is easiest to follow.
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_student.py` line 39 at r5](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpVQn3y3kkLWr2Ld5SJ:-NpYxThM0Rh6Q3WZ3pRQ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/5404604c90912545ec6078d349dd92fce18c6239/backend/api/tests/serializers/test_student.py#L39)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

"to a class"
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_student.py` line 64 at r5](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpVRd6V6NFoX2lYv5qg:-NpYxZ9t05LNGb1SBjoT:b9cunfs) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/5404604c90912545ec6078d349dd92fce18c6239/backend/api/tests/serializers/test_student.py#L64)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

assert klass has different school to teacher's
</blockquote></details>

don't need to as I'm already ensuring that with the exclude(). therefore, we can be sure about the state of the data.
___
*[`backend/api/tests/serializers/test_student.py` line 89 at r5](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259#-NpVRiiE7bRc6yjV8Etm:-NpYxqDW7MPTENHoJZ4S:b9cunfs) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/5404604c90912545ec6078d349dd92fce18c6239/backend/api/tests/serializers/test_student.py#L89)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

assert klass teacher isn't request teacher
</blockquote></details>

don't need to as I'm already ensuring that with the exclude(). therefore, we can be sure about the state of the data.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/259)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
