### PR TITLE
feat: integrated the score view for the students and student login

### PR DESCRIPTION
**Pull request by KamilPawel**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150)

### CODE REVIEW

**Review by cewei8483 — CHANGES_REQUESTED** [review]
Please fix ESlint errors

> Reviewed 4 of 17 files at r3, 3 of 14 files at r4, 3 of 10 files at r5, 1 of 4 files at r6, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-:-NdoUBriCIHtMj0i_xu3:b79nxpa)* status: 12 of 28 files reviewed, 13 unresolved discussions (waiting on @KamilPawel)

___
*[`.vscode/settings.json` line 2 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NdoUGXd6xCW3tiQcg2O:-NdoUGXd6xCW3tiQcg2P:bzbe37d) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/.vscode/settings.json#L2)):*
> ```JSON
> {
>   "standard.engine": "ts-standard",
> ```

What is this for?
___
*[`backend/portal/urls/registration.py` line 33 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndo_ZXK7O6BlFF3Udr_:-Ndo_ZXL4H_xssvO7pud:b-wut2bt) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/urls/registration.py#L33)):*
> ```Python
>         name="delete_account",
>     ),
>     path("verify-password/", verify_password, name=verify_password.__name__),
> ```

Maybe just use string instead rather than __name__
___
*[`backend/portal/urls/student.py` line 31 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndp7zGv8NUjLkR9Xv-T:-Ndp7zGv8NUjLkR9Xv-U:bz5bn6g) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/urls/student.py#L31)):*
> ```Python
>     path(
>         "school-student/edit-details/",
>         SchoolStudentEditAccountView.as_view(),
> ```

Change this to the name of the view instead of calling as_view()?
___
*[`backend/portal/views/student/edit_account_details.py` line 168 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndp8qGk2CJi_Hf38t4o:-Ndp8qGk2CJi_Hf38t4p:b4p2sg) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/views/student/edit_account_details.py#L168)):*
> ```Python
> 
> 
> def process_change_email_password_form(request, student, old_anchor):
> ```

There's also one `anchor` variable in my view however I found it useless. If it does nothing in your case too then you can remove it.
___
*[`backend/portal/views/student/edit_account_details.py` line 205 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndp9Rn8AU2USGkV0wdq:-Ndp9Rn8AU2USGkV0wdr:b-9fum3u) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/views/student/edit_account_details.py#L205)):*
> ```Python
>         check_update_password(form_class, request.user, request, data)
>     else:
>         print(form_class.errors)
> ```

remove print
___
*[`backend/portal/views/student/edit_account_details.py` line 222 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndp8aGgClxJPcqN9NiL:-Ndp8aGgClxJPcqN9NiM:bbj4nzs) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/views/student/edit_account_details.py#L222)):*
> ```Python
> 
> def change_school_student_details(request):
>     return process_student_edit_account_form(request)
> ```

Could you replace this function with `process_student_edit_account_form` since they're identical?
___
*[`backend/portal/views/student/play.py` line 90 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NdpAIUi6IF3E0qoRKtf:-NdpAIUi6IF3E0qoRKtg:b-a90qis) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/views/student/play.py#L90)):*
> ```Python
> 
> 
> def username_labeller(request):
> ```

Is this function being called elsewhere?
___
*[`backend/portal/views/student/play.py` line 99 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NdpALbr7cN378WgRBI1:-NdpALbr7cN378WgRBI2:b-owp118) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/views/student/play.py#L99)):*
> ```Python
>     login_url=reverse_lazy("independent_student_login"),
> )
> def student_join_organisation(request):
> ```

Check this one as well (and consequently `process_join_organisation_form`)
If it is being called then it shouldn't return html
___
*[`backend/portal/views/student/play.py` line 165 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NdpAq2x9QO4LKz5Vjn2:-NdpAq2x9QO4LKz5Vjn3:b-ee9smz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/views/student/play.py#L165)):*
> ```Python
> 
> 
> def show_cancellation_message_if_student_not_in_class(student, request):
> ```

this one as well
___
*[`frontend/src/features/deleteAccountForm/DeleteAccountForm.tsx` line 103 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndosk8k6EQbWxBkDRlX:-Ndosk8k6EQbWxBkDRlY:b-lsss4j) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/frontend/src/features/deleteAccountForm/DeleteAccountForm.tsx#L103)):*
> ```XML
>                 userType="independent"
>               />
>               ;
> ```

Unnecessary semicolon?
___
*[`frontend/src/pages/studentDashboard/KuronoProgress.tsx` line 21 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NdoeGhT1GLwObJcBnaH:-NdoeGhT1GLwObJcBnaI:b-928zzo) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/frontend/src/pages/studentDashboard/KuronoProgress.tsx#L21)):*
> ```XML
>     return <>
>       <Typography variant='h4'>
> ```

Empty line
___
*[`frontend/src/pages/studentDashboard/account/StudentAccount.tsx` line 173 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NdoqWAk2UpdEooojF1Q:-NdoqWAk2UpdEooojF1R:b-q6ov8p) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/frontend/src/pages/studentDashboard/account/StudentAccount.tsx#L173)):*
> ```XML
>     };
>     const [updateStudent] = useUpdateStudentDetailsMutation();
>     // const [logoutMutation] = useLogoutUserMutation();
> ```

Is this endpoint implemented?
___
*[`frontend/src/pages/teacherDashboard/account/YourAccount.tsx` line 114 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndoq9wJ0TOxgXOCFBbj:-Ndoq9wJ0TOxgXOCFBbk:b-wj3fa2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/frontend/src/pages/teacherDashboard/account/YourAccount.tsx#L114)):*
> ```XML
> 
>   const theme = useTheme();
>   return (
> ```

This file is inside teacher dashboard, please revert it

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150)* status: 9 of 31 files reviewed, 13 unresolved discussions (waiting on @cewei8483)

___
*[`.vscode/settings.json` line 2 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NdoUGXd6xCW3tiQcg2O:-Ne2l7aR8iAD6WO3nCwh:b-ahpzhe) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/.vscode/settings.json#L2)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

This I'll revert, I was tying to setup my eslint :sweat_smile: 
___
*[`backend/portal/urls/registration.py` line 33 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndo_ZXK7O6BlFF3Udr_:-Ne2lUo6-Cr6VwyViklR:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/urls/registration.py#L33)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Maybe just use string instead rather than __name__
</blockquote></details>

Done.
___
*[`backend/portal/urls/student.py` line 31 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndp7zGv8NUjLkR9Xv-T:-Ne3mX9sCPN0qHVwwjGX:bn1z6ol) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/urls/student.py#L31)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Change this to the name of the view instead of calling as_view()?
</blockquote></details>

It did not work for me :/
___
*[`backend/portal/views/student/edit_account_details.py` line 168 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndp8qGk2CJi_Hf38t4o:-Ne2zuLR2N9x5arJ4RoC:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/views/student/edit_account_details.py#L168)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

There's also one `anchor` variable in my view however I found it useless. If it does nothing in your case too then you can remove it.
</blockquote></details>

Done.
___
*[`backend/portal/views/student/edit_account_details.py` line 205 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndp9Rn8AU2USGkV0wdq:-Ne3B3FH4wMHf5KzhOOY:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/views/student/edit_account_details.py#L205)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

remove print
</blockquote></details>

Done.
___
*[`backend/portal/views/student/edit_account_details.py` line 222 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndp8aGgClxJPcqN9NiL:-Ne3A9B771UEEqDvfe4Q:bei7p1p) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/views/student/edit_account_details.py#L222)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Could you replace this function with `process_student_edit_account_form` since they're identical?
</blockquote></details>

But they do include different forms no?
___
*[`backend/portal/views/student/play.py` line 90 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NdpAIUi6IF3E0qoRKtf:-Ne3AI0x0z5QnSDsdcw6:bb710yj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/views/student/play.py#L90)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Is this function being called elsewhere?
</blockquote></details>

Nope
___
*[`backend/portal/views/student/play.py` line 99 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NdpALbr7cN378WgRBI1:-Ne3mIN-7aE1RnNcCV7-:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/views/student/play.py#L99)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Check this one as well (and consequently `process_join_organisation_form`)
If it is being called then it shouldn't return html
</blockquote></details>

Done.
___
*[`backend/portal/views/student/play.py` line 165 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NdpAq2x9QO4LKz5Vjn2:-Ne3mOj405SYvTrl6LkK:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/backend/portal/views/student/play.py#L165)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

this one as well
</blockquote></details>

Done.
___
*[`frontend/src/features/deleteAccountForm/DeleteAccountForm.tsx` line 103 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndosk8k6EQbWxBkDRlX:-Ne3mTpO4R-oz-Up867U:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/frontend/src/features/deleteAccountForm/DeleteAccountForm.tsx#L103)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Unnecessary semicolon?
</blockquote></details>

Done.
___
*[`frontend/src/pages/studentDashboard/KuronoProgress.tsx` line 21 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NdoeGhT1GLwObJcBnaH:-Ne2mmlx5wT6fCUjRkI3:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/frontend/src/pages/studentDashboard/KuronoProgress.tsx#L21)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Empty line
</blockquote></details>

Done.
___
*[`frontend/src/pages/studentDashboard/account/StudentAccount.tsx` line 173 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NdoqWAk2UpdEooojF1Q:-Ne2nZDK5srcEFa6SRLC:b-brgcg4) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/frontend/src/pages/studentDashboard/account/StudentAccount.tsx#L173)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Is this endpoint implemented?
</blockquote></details>

seems it is :)
___
*[`frontend/src/pages/teacherDashboard/account/YourAccount.tsx` line 114 at r7](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ndoq9wJ0TOxgXOCFBbj:-Ne3nG5d9OM8oGFfxkkO:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/95601992076c72f328d4ffee8acd52852a7602ef/frontend/src/pages/teacherDashboard/account/YourAccount.tsx#L114)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

This file is inside teacher dashboard, please revert it
</blockquote></details>

Done.

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150)* status: 7 of 31 files reviewed, 2 unresolved discussions (waiting on @cewei8483)

___
*[`backend/service/settings.py` line 74 at r8](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne3wDsk03vu5cLKajk0:-Ne44cfXEtOviDFpRYKe:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f5a2a1713b7ea46536f7a8ce416055b316a3addc/backend/service/settings.py#L74)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

uncomment?
</blockquote></details>

Done.

**Review by cewei8483 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150)* status: 6 of 31 files reviewed, 8 unresolved discussions (waiting on @KamilPawel)

___
*[`backend/portal/views/student/play.py` line 111 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9jj-N8M7LwmA8NW3t:-Ne9jj-N8M7LwmA8NW3u:bltmsrt) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/backend/portal/views/student/play.py#L111)):*
> ```Python
>             student.pending_class_request = None
>             student.save()
>             # Check teacher hasn't since accepted rejection before posting success
> ```

Is this a TODO?
___
*[`backend/portal/views/student/play.py` line 121 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9jbb7-HRifzKmpIqS:-Ne9jbb7-HRifzKmpIqT:ben9jy6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/backend/portal/views/student/play.py#L121)):*
> ```Python
>     #     {"request_form": request_form, "student": student},
>     # )
>     return HttpResponse(status=status.HTTP_405_METHOD_NOT_ALLOWED)  # res
> ```

remove unnecessary comment
___
*[`frontend/src/pages/studentDashboard/account/StudentAccount.tsx` line 122 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9g-uHAIclmP34iQQd:-Ne9g-uHAIclmP34iQQe:b-dbr8i9) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/frontend/src/pages/studentDashboard/account/StudentAccount.tsx#L122)):*
> ```XML
>       <Form
>         initialValues={initialValues}
>         onSubmit={(values, formik) => {
> ```

remove unused variable
___
*[`frontend/src/pages/studentDashboard/account/StudentAccount.tsx` line 127 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9gLij70wBLn__plvM:-Ne9gLij70wBLn__plvN:b-dbr8i9) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/frontend/src/pages/studentDashboard/account/StudentAccount.tsx#L127)):*
> ```XML
>           updateSchoolStudent(values)
>             .unwrap()
>             .then((res) => {
> ```

remove unused variable
___
*[`frontend/src/pages/studentDashboard/account/StudentAccount.tsx` line 203 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9iMK8EeXkvEHAgmor:-Ne9iMK8EeXkvEHAgmos:b-5oenxo) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/frontend/src/pages/studentDashboard/account/StudentAccount.tsx#L203)):*
> ```XML
>             });
> 
>           updateStudent(values)
> ```

BE complains`TypeError: process_change_email_password_form() takes 2 positional arguments but 3 were given` when I tried to modify name
___
*[`frontend/src/pages/studentDashboard/account/StudentAccount.tsx` line 276 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9fLL1B3eZ0jCMOQjX:-Ne9fLL1B3eZ0jCMOQjY:bwbmdie) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/frontend/src/pages/studentDashboard/account/StudentAccount.tsx#L276)):*
> ```XML
>       <Page.Section>
>         {isDependent
> ? (
> ```

indentation (same below)
___
*[`frontend/src/pages/studentDashboard/joinSchool/JoinSchool.tsx` line 76 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9k4CSEMqRWSm8lfzX:-Ne9k4CSEMqRWSm8lfzY:b-rr7e9n) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/frontend/src/pages/studentDashboard/joinSchool/JoinSchool.tsx#L76)):*
> ```XML
>                   .unwrap()
>                   .then(() => {
>                     setRequestSent(true);
> ```

Page should be refreshed after submit so that latest status is shown
also remove finished TODOs
___
*[`.vscode/settings.json` line 15 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9kt5y8FaXO15E5_Oq:-Ne9kt5y8FaXO15E5_Or:b-4yr6dt) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/.vscode/settings.json#L15)):*
> ```JSON
>     "python.testing.unittestEnabled": false,
>     "python.testing.pytestEnabled": true
> }
> ```

newline

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150)* status: 5 of 33 files reviewed, 8 unresolved discussions (waiting on @cewei8483)

___
*[`backend/portal/views/student/play.py` line 111 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9jj-N8M7LwmA8NW3t:-NeDYvAE9MQ3Ar7Ub3iO:b-16ljwl) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/backend/portal/views/student/play.py#L111)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Is this a TODO?
</blockquote></details>

That is the comment for the previous code i'll remove the comments though as you said below 
___
*[`backend/portal/views/student/play.py` line 121 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9jbb7-HRifzKmpIqS:-NeDZbB0DT-QMa4NvXSw:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/backend/portal/views/student/play.py#L121)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

remove unnecessary comment
</blockquote></details>

Done.
___
*[`frontend/src/pages/studentDashboard/account/StudentAccount.tsx` line 122 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9g-uHAIclmP34iQQd:-NeDZnqTE1Q_asOrgz3T:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/frontend/src/pages/studentDashboard/account/StudentAccount.tsx#L122)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

remove unused variable
</blockquote></details>

Done.
___
*[`frontend/src/pages/studentDashboard/account/StudentAccount.tsx` line 127 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9gLij70wBLn__plvM:-NeDZrGe3IbEUW1sALWM:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/frontend/src/pages/studentDashboard/account/StudentAccount.tsx#L127)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

remove unused variable
</blockquote></details>

Done.
___
*[`frontend/src/pages/studentDashboard/account/StudentAccount.tsx` line 203 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9iMK8EeXkvEHAgmor:-NeDadqrCn_x5gt5gR1B:bb6un1j) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/frontend/src/pages/studentDashboard/account/StudentAccount.tsx#L203)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

BE complains`TypeError: process_change_email_password_form() takes 2 positional arguments but 3 were given` when I tried to modify name
</blockquote></details>

Done
___
*[`frontend/src/pages/studentDashboard/account/StudentAccount.tsx` line 276 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9fLL1B3eZ0jCMOQjX:-NeDkW233XivGrRS0D5Q:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/frontend/src/pages/studentDashboard/account/StudentAccount.tsx#L276)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

indentation (same below)
</blockquote></details>

Done.
___
*[`frontend/src/pages/studentDashboard/joinSchool/JoinSchool.tsx` line 76 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9k4CSEMqRWSm8lfzX:-NeDbIps8iXq5Arbm_vF:bsl476w) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/frontend/src/pages/studentDashboard/joinSchool/JoinSchool.tsx#L76)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Page should be refreshed after submit so that latest status is shown
also remove finished TODOs
</blockquote></details>

I called the refetch now :)
___
*[`.vscode/settings.json` line 15 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9kt5y8FaXO15E5_Oq:-NeDkbY41oQae88YjNDA:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/.vscode/settings.json#L15)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

newline
</blockquote></details>

Done.

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150)* status: 5 of 33 files reviewed, 5 unresolved discussions (waiting on @cewei8483)

___
*[`backend/portal/views/student/edit_account_details.py` line 244 at r12](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NeEFLJH7T1AGft_99f5:-NeOD9L48tUN62-GP20v:beu7feq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d671c29326e6236afb568066ff292b02a14fa65e/backend/portal/views/student/edit_account_details.py#L244)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Just checking if you want to ignore the return values
</blockquote></details>

They were mainly used for the messages which we handle at the frontend now
___
*[`backend/portal/views/student/edit_account_details.py` line 258 at r12](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NeEG_lM5tOjlxURwr59:-NeNufhy8Vg8uIpens_X:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d671c29326e6236afb568066ff292b02a14fa65e/backend/portal/views/student/edit_account_details.py#L258)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

delete django messages as they are of no use anyways
</blockquote></details>

Done.
___
*[`frontend/src/pages/studentDashboard/BaseDashboard.tsx` line 76 at r12](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NeECcPHBZaxljK1eGrd:-NeNui5f4-dKNFD0qDmY:b-1zpjwc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d671c29326e6236afb568066ff292b02a14fa65e/frontend/src/pages/studentDashboard/BaseDashboard.tsx#L76)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Does the notification still shows after an independent student send a request?
</blockquote></details>

Yes it is rendered on default as you log in and does not disappear 
___
*[`frontend/src/pages/studentDashboard/account/StudentAccount.tsx` line 203 at r10](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-Ne9iMK8EeXkvEHAgmor:-NeNPGUlAlrMgTcp8Z5v:b-q4jwx4) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/975879d7f0c8df4ed99682495c3e8e0630c6a25f/frontend/src/pages/studentDashboard/account/StudentAccount.tsx#L203)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

There is no error but the user data is not being updated :cry:
</blockquote></details>

notification was not working so I updated it 
___
*[`frontend/src/pages/studentDashboard/joinSchool/JoinSchool.tsx` line 42 at r12](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-NeEAeGv1k_oSmeGVZxH:-NeNuq7X8o0R27_8W1Fb:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d671c29326e6236afb568066ff292b02a14fa65e/frontend/src/pages/studentDashboard/joinSchool/JoinSchool.tsx#L42)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

It isn't showing the access code that I filled in the form
</blockquote></details>

Done.

**Review by cewei8483 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 17 files at r3, 3 of 14 files at r4, 2 of 10 files at r5, 8 of 16 files at r8, 2 of 6 files at r10, 5 of 8 files at r11, 1 of 4 files at r12, 1 of 1 files at r13, 2 of 2 files at r15, 2 of 2 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/150#-:-NeOQXC5-51PXiqh3Z1S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Pull request merged**
