### PR TITLE
feat: 17 email views

### PR DESCRIPTION
**Pull request by cewei8483**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76)

### CODE REVIEW

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 1 of 10 files at r1, 1 of 3 files at r2, 6 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76)* status: 8 of 13 files reviewed, 5 unresolved discussions (waiting on @cewei8483)

___
*[`.gitignore` line 209 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76#-N_t1k2rAgRfEcBBH2cy:-N_t1k2rAgRfEcBBH2cz:b9jipst) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/39a035d3a7f1503302bc8aa51de0771d806f4c66/.gitignore#L209)):*
> ```ignore
> /package.json
> /yarn.lock
> __pycache__
> ```

2 things.
1. you put this in the frontend section of the .gitignore
2. this is already the first thing listed in the backend section
___
*[`.vscode/launch.json` line 8 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76#-N_t2PO86SZ5il7Hy_hF:-N_t2PO86SZ5il7Hy_hG:bl0ifoa) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/39a035d3a7f1503302bc8aa51de0771d806f4c66/.vscode/launch.json#L8)):*
> ```JSON
>   "configurations": [
>     {
>       "name": "Python: Django",
> ```

already included below
___
*[`backend/portal/urls/email.py` line 11 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76#-N_t2cDY7S-NSt1hmDWL:-N_t2cDY7S-NSt1hmDWM:b-jqbbki) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/39a035d3a7f1503302bc8aa51de0771d806f4c66/backend/portal/urls/email.py#L11)):*
> ```Python
> urlpatterns = [  
>     re_path(
>         # TODO: modify urls in the verification email
> ```

 please do that [here](https://github.com/ocadotechnology/codeforlife-portal-react/blob/17-email-views/backend/portal/email_messages.py)

we moved the email_messages.py file from common to the portal app so we can make edits to the emails.
___
*[`frontend/src/app/api/endpoints/dotmailer.ts` line 8 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76#-N_tAQJuBipSYxoTzN9V:-N_tAQJuBipSYxoTzN9W:b8o46cx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f2effeaa63657b9c5d914f6629686d1f4d3c7625/frontend/src/app/api/endpoints/dotmailer.ts#L8)):*
> ```XML
>   endpoints: (build) => ({
>     // TODO: set body and response types
>     signUp: build.mutation({
> ```

please rename this to subscribeToNewsletter. The names should be as clear as possible for readable code. Otherwise, useSignUpMutation makes me think you're creating a new user account.
___
*[`frontend/src/pages/login/Login.tsx` line 39 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76#-N_tBa1W-ylNVkw0d3E5:-N_tBa1W-ylNVkw0d3E6:b-doub88) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/39a035d3a7f1503302bc8aa51de0771d806f4c66/frontend/src/pages/login/Login.tsx#L39)):*
> ```XML
>     <Page.Container>
>       {
>         searchParams?.verifyEmail
> ```

simpler syntax.

{searchParams?.verifyEmail === true &&
    <Page.Notification>
        Your email address was successfully verified, please log in.
    </Page.Notification>
}

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76)* status: 8 of 15 files reviewed, 5 unresolved discussions (waiting on @SKairinos)

___
*[`backend/portal/urls/email.py` line 11 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76#-N_t2cDY7S-NSt1hmDWL:-Na6Q4_N65VF99iI7fuw:b-i96d46) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/39a035d3a7f1503302bc8aa51de0771d806f4c66/backend/portal/urls/email.py#L11)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

 please do that [here](https://github.com/ocadotechnology/codeforlife-portal-react/blob/17-email-views/backend/portal/email_messages.py)

we moved the email_messages.py file from common to the portal app so we can make edits to the emails.
</blockquote></details>

It turns out that django reverse has already done the job.
___
*[`frontend/src/app/api/endpoints/dotmailer.ts` line 8 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76#-N_tAQJuBipSYxoTzN9V:-Na6Q3qZ54y4e0VNFUBJ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f2effeaa63657b9c5d914f6629686d1f4d3c7625/frontend/src/app/api/endpoints/dotmailer.ts#L8)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

please rename this to subscribeToNewsletter. The names should be as clear as possible for readable code. Otherwise, useSignUpMutation makes me think you're creating a new user account.
</blockquote></details>

Done.
___
*[`frontend/src/pages/login/Login.tsx` line 39 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76#-N_tBa1W-ylNVkw0d3E5:-Na6Q-It-bTLUmapnP-P:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/39a035d3a7f1503302bc8aa51de0771d806f4c66/frontend/src/pages/login/Login.tsx#L39)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

simpler syntax.

{searchParams?.verifyEmail === true &&
    <Page.Notification>
        Your email address was successfully verified, please log in.
    </Page.Notification>
}
</blockquote></details>

Done.
___
*[`.gitignore` line 209 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76#-N_t1k2rAgRfEcBBH2cy:-Na6Q01C0cnGgqLrrgV4:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/39a035d3a7f1503302bc8aa51de0771d806f4c66/.gitignore#L209)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

2 things.
1. you put this in the frontend section of the .gitignore
2. this is already the first thing listed in the backend section
</blockquote></details>

Done.
___
*[`.vscode/launch.json` line 8 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76#-N_t2PO86SZ5il7Hy_hF:-Na6Q2417BOlHTG_hyyt:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/39a035d3a7f1503302bc8aa51de0771d806f4c66/.vscode/launch.json#L8)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

already included below
</blockquote></details>

Done.

**Review by SKairinos — COMMENTED** [review]
> Reviewed 6 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76)* status: 14 of 15 files reviewed, 1 unresolved discussion

**Review by SKairinos — APPROVED** [review]
> Reviewed 1 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/76)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Pull request merged**
