### PR TITLE
Registration views

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78)* status: 0 of 50 files reviewed, 3 unresolved discussions

___
*[`backend/portal/views/registration.py` line 162 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_hX5C54lh4iwxjTDg6:-N_hX5C54lh4iwxjTDg7:b8k7dwx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/views/registration.py#L162)):*
> ```Python
>             #     {"usertype": usertype},
>             # )
>             return HttpResponse(status=status.HTTP_200_OK)
> ```

return HTTP 204 no content
___
*[`backend/portal/views/registration.py` line 251 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_hZN2eEc-PqTW_A18J:-N_hZJnO78N5BxjcTeDY:brhc0wb) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/views/registration.py#L251)):*
> ```Python
>                 # )
> 
>     return HttpResponse(status=status.HTTP_500_INTERNAL_SERVER_ERROR)
> ```

400 bad request error
___
*[`backend/portal/views/registration.py` line 328 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_h_3br7VV_ThJ0CuU4:-N_h_3br7VV_ThJ0CuU5:bhu3bpn) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/views/registration.py#L328)):*
> ```Python
>     password = request.POST.get("password")
> 
>     # TODO: handle this feedback.
> ```

create endpoint to validate user's password. also validate password in this endpoint

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 50 of 50 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78)* status: all files reviewed, 11 unresolved discussions (waiting on @SKairinos)

___
*[`backend/portal/forms/registration.py` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i2VkX2m5344q7Cy-_:-N_i2VkX2m5344q7Cy-a:b-dq46a1) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/forms/registration.py#L1)):*
> ```Python
> from captcha.fields import ReCaptchaField
> ```

A general question about this file - is there even still a point in defining the form fields? If they are defined in the frontend now, what's the point of having them here?
___
*[`backend/portal/forms/registration.py` line 49 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i1fnu2Wtb-E5TmSPm:-N_i1fnv-TVRAxhiFPSN:b-uzgk15) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/forms/registration.py#L49)):*
> ```Python
> 
>     # TODO: assess whether this is needed
>     # captcha = ReCaptchaField(widget=ReCaptchaV2Invisible)
> ```

Not needed, you can delete
___
*[`backend/portal/forms/registration.py` line 61 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i1mE74ZNDxV_Q4EHB:-N_i1mE74ZNDxV_Q4EHC:b27zlut) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/forms/registration.py#L61)):*
> ```Python
>         request=None,
>         html_email_template_name="portal/reset_password_email.html",
>     ):
> ```

Looks like a few args aren't used here. Namely
`subject_template`
`email_template_name`
`from_email` and
`html_email_template_name`

I know it was originally like that though so we can leave it if we say we're gonna clean it later



_Code quote:_
```Python
    def save(
        self,
        domain_override=None,
        subject_template_name=None,
        email_template_name="portal/reset_password_email.txt",
        use_https=False,
        token_generator=default_token_generator,
        from_email=None,
        request=None,
        html_email_template_name="portal/reset_password_email.html",
    ):
```
___
*[`backend/portal/helpers/password.py` line 10 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i2p3BDOTR_Nh9oje2:-N_i2p3BDOTR_Nh9oje3:bt0duyv) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/helpers/password.py#L10)):*
> ```Python
> 
> 
> import hashlib
> ```

I think you can reorg these imports
___
*[`backend/portal/helpers/password.py` line 104 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i38a4-PHKqTy9ASbW:-N_i38a4-PHKqTy9ASbX:bvpc4gg) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/helpers/password.py#L104)):*
> ```Python
> 
> 
> def password_strength_test(
> ```

I should've pointed this out in Kamil's task but we don't need the list of `most_used_passwords` below anymore since we now have the pwned passwords logic.
___
*[`backend/portal/urls/registration.py` line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i3h8-0kvpX7jpXAwy:-N_i3h8-0kvpX7jpXAwz:blrfw1x) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/urls/registration.py#L23)):*
> ```Python
>         name="teacher_password_reset",
>     ),
>     # TODO: confirm this is not needed.
> ```

You should be able to remove this
___
*[`backend/portal/views/registration.py` line 7 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i48OM3ySKBFxv9E4R:-N_i48OM3ySKBFxv9E4S:b-j1nvve) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/views/registration.py#L7)):*
> ```Python
> from portal.views.login import has_user_lockout_expired
> 
> from django.contrib.auth.models import User
> ```

I think you can remove this import
___
*[`backend/portal/views/registration.py` line 142 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i4GEn5Q_gX40XUztN:-N_i4GEn5Q_gX40XUztO:bkoh63o) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/views/registration.py#L142)):*
> ```Python
>         handle_reset_password_tracking(request, usertype)
>         form = password_reset_form(request.POST)
>         # TODO: assess whether this is needed
> ```

You can remove this

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78)* status: 42 of 55 files reviewed, 10 unresolved discussions (waiting on @faucomte97)

___
*[`backend/portal/forms/registration.py` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i2VkX2m5344q7Cy-_:-N_mwL4W5K0BUJz8g_jr:b51qvdl) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/forms/registration.py#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

A general question about this file - is there even still a point in defining the form fields? If they are defined in the frontend now, what's the point of having them here?
</blockquote></details>

We want to do form validation on the front and back end, no? This way, it's impossible to make invalid requests to the backend
___
*[`backend/portal/forms/registration.py` line 61 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i1mE74ZNDxV_Q4EHB:-N_mwd678s5gnys3zgMs:b-t5avvy) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/forms/registration.py#L61)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Looks like a few args aren't used here. Namely
`subject_template`
`email_template_name`
`from_email` and
`html_email_template_name`

I know it was originally like that though so we can leave it if we say we're gonna clean it later
</blockquote></details>

I say let's leave it just to avoid unconsidered issues cropping up. Let's copy everything, warts and all.
___
*[`backend/portal/helpers/password.py` line 10 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i2p3BDOTR_Nh9oje2:-N_mxKc_3vLNaiDmShA_:b-s1uz2x) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/helpers/password.py#L10)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I think you can reorg these imports
</blockquote></details>

Let's have a separate convo about import ordering. Have been meaning to discuss it for a while
___
*[`backend/portal/helpers/password.py` line 104 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i38a4-PHKqTy9ASbW:-N_mxeOV4gehHz2Xl6g5:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/helpers/password.py#L104)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I should've pointed this out in Kamil's task but we don't need the list of `most_used_passwords` below anymore since we now have the pwned passwords logic.
</blockquote></details>

Done.
___
*[`backend/portal/urls/registration.py` line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i3h8-0kvpX7jpXAwy:-N_mxlem2qGwPg-Ayjvk:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/urls/registration.py#L23)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You should be able to remove this
</blockquote></details>

Done.
___
*[`backend/portal/views/registration.py` line 7 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i48OM3ySKBFxv9E4R:-N_mxtD890b8gWTVsP_H:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/views/registration.py#L7)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I think you can remove this import
</blockquote></details>

Done.
___
*[`backend/portal/views/registration.py` line 251 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_hZN2eEc-PqTW_A18J:-N_myKrr0IBV0-JM111k:b-it1cqr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/views/registration.py#L251)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

400 bad request error
</blockquote></details>

changed to 403 forbidden instead if the user is not authenticated.
___
*[`backend/portal/views/registration.py` line 328 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_h_3br7VV_ThJ0CuU4:-N_myQAJ2mZcjWWQgLU5:ba33xr0) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/views/registration.py#L328)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

create endpoint to validate user's password. also validate password in this endpoint
</blockquote></details>

handled 400 bad request in the same endpoint now

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78)* status: 42 of 55 files reviewed, 10 unresolved discussions (waiting on @faucomte97)

___
*[`backend/portal/forms/registration.py` line 49 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i1fnu2Wtb-E5TmSPm:-N_n5xaV6CYiCUgcDtuD:bpk15bk) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/forms/registration.py#L49)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Not needed, you can delete
</blockquote></details>

Done. Going to keep it commented out, however, to remind us it once there
___
*[`backend/portal/views/registration.py` line 142 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_i4GEn5Q_gX40XUztN:-N_n6Gq77yqzI8B-kEVI:b-22kw9q) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bba3998106ea5ca5dee8e61a28c225c9a939f48f/backend/portal/views/registration.py#L142)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You can remove this
</blockquote></details>

Done.Going to keep it commented out, however, to remind us it once there

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r2, 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78)* status: all files reviewed, 5 unresolved discussions (waiting on @SKairinos)

___
*[`backend/portal/forms/registration.py` line 158 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_nAcv4AVr69kF5qdm0:-N_nAcv4AVr69kF5qdm1:bze3u9) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/96fc44c3f45795313e5aa86c552b28910b16cbb6/backend/portal/forms/registration.py#L158)):*
> ```Python
>             raise forms.ValidationError("Incorrect password")
> 
> # http://example.com/?userId=Mg&amp;token=brn00a-928bb157565b01dcae8ec21fc312f183
> ```

lol :upside_down_face: 
___
*[`backend/portal/helpers/password.py` line 18 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_nAgxB2M4qK1dD6X6Y:-N_nAgxB2M4qK1dD6X6Z:b-vmiien) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/96fc44c3f45795313e5aa86c552b28910b16cbb6/backend/portal/helpers/password.py#L18)):*
> ```Python
>     sha1_hash = hashlib.sha1(password.encode()).hexdigest()
>     prefix = sha1_hash[
>         :5
> ```

that's a weird bit of formatting o.O
___
*[`backend/portal/views/registration.py` line 199 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_nAvBZ016GQFa632JA:-N_nAvBZ016GQFa632JB:bb2w7zq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/96fc44c3f45795313e5aa86c552b28910b16cbb6/backend/portal/views/registration.py#L199)):*
> ```Python
> #     update_context_and_apps(request, context, current_app, extra_context)
> 
> #     return TemplateResponse(request, template_name, context)
> ```

Remove this? Optional
___
*[`frontend/src/app/api/baseQuery.ts` line 22 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_nB2Gp52egbBacAkAs:-N_nB2Gp52egbBacAkAt:b2ni54z) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/96fc44c3f45795313e5aa86c552b28910b16cbb6/frontend/src/app/api/baseQuery.ts#L22)):*
> ```XML
>   FetchBaseQueryError
> > = async (args, api, extraOptions) => {
>   // Check if the request has a body and it's content type is specified.
> ```

its
___
*[`frontend/src/app/api/baseQuery.ts` line 27 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_nB31T0F23BHXA6EkO:-N_nB31T0F23BHXA6EkP:b2ni54z) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/96fc44c3f45795313e5aa86c552b28910b16cbb6/frontend/src/app/api/baseQuery.ts#L27)):*
> ```XML
>     'Content-Type' in args.headers
>   ) {
>     // Stringify the request body based on it's content type.
> ```

its

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78)* status: 55 of 56 files reviewed, 5 unresolved discussions (waiting on @faucomte97)

___
*[`backend/portal/forms/registration.py` line 158 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_nAcv4AVr69kF5qdm0:-N_nBaHmAAS813CMt72r:b8efsp2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/96fc44c3f45795313e5aa86c552b28910b16cbb6/backend/portal/forms/registration.py#L158)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

lol :upside_down_face: 
</blockquote></details>

oops. removed
___
*[`backend/portal/helpers/password.py` line 18 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_nAgxB2M4qK1dD6X6Y:-N_nBj9cA3YVrL7KYqPz:buvlw0c) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/96fc44c3f45795313e5aa86c552b28910b16cbb6/backend/portal/helpers/password.py#L18)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

that's a weird bit of formatting o.O
</blockquote></details>

that's black doing the formatting  [###  ¯\\\_(ツ)\_/¯
___
*[`backend/portal/views/registration.py` line 199 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_nAvBZ016GQFa632JA:-N_nBs9PEwXeVUxywlu_:b-gy9f5j) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/96fc44c3f45795313e5aa86c552b28910b16cbb6/backend/portal/views/registration.py#L199)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove this? Optional
</blockquote></details>

going to keep all the old code as comments so we can backtrack if something goes wrong
___
*[`frontend/src/app/api/baseQuery.ts` line 22 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_nB2Gp52egbBacAkAs:-N_nBxp9AyQBPvCdGQlK:bd1shdu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/96fc44c3f45795313e5aa86c552b28910b16cbb6/frontend/src/app/api/baseQuery.ts#L22)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

its
</blockquote></details>

grammar police! ;P haha
___
*[`frontend/src/app/api/baseQuery.ts` line 27 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-N_nB31T0F23BHXA6EkO:-N_nCAgv01tglhU8ptbs:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/96fc44c3f45795313e5aa86c552b28910b16cbb6/frontend/src/app/api/baseQuery.ts#L27)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

its
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78#-:-N_nCtk3EOfBTsJZozng:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
