### PR TITLE
fix: altered the padding to match prod

### PR DESCRIPTION
**Pull request by KamilPawel**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138)

### CODE REVIEW

**Review by cewei8483 — CHANGES_REQUESTED** [review]
Please adjust `Page.Section` paddings based on the latest js package since the issue has been addressed before.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-:-NbU7Z-88ZRa15TOCNtG:bimgq1f)* status: all files reviewed, 6 unresolved discussions (waiting on @KamilPawel)

___
*[`frontend/src/components/Introduction.tsx` line 28 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU9Wh_8fvnP02OapT7:-NbU9WhaCPCJ0TZCU0Xt:bah7ic6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/components/Introduction.tsx#L28)):*
> ```XML
>         <Grid xs={12} md={6}>
>           <Stack sx={{ height: '100%' }}>
>             <Typography sx={{ lineHeight: 0.7 }} variant="h5">
> ```

Is this about the alignment issue?
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 147 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU5AWkC9p8EUqfrKN4:-NbU5AWkC9p8EUqfrKN5:bwlrvlj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/pages/teacherDashboard/YourSchool.tsx#L147)):*
> ```XML
>       <>
>         <Button endIcon={<Add />}>Make admin </Button>
>         {twoFactorAuthentication ? (
> ```

ESlint complaint: `Expected newline between test and consequent of ternary expressio` [multiline-ternary](https://eslint.org/docs/latest/rules/multiline-ternary)
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 214 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU79wMDzlU4wNi77d4:-NbU79wMDzlU4wNi77d5:beqivry) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/pages/teacherDashboard/YourSchool.tsx#L214)):*
> ```XML
>     <>
>       <Page.Section
>         sx={{
> ```

See review discussion
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 217 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU5xKsCZdmV_5raUsT:-NbU5xKsCZdmV_5raUsU:b61lt4f) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/pages/teacherDashboard/YourSchool.tsx#L217)):*
> ```XML
>           paddingTop: theme.spacing(6),
>           paddingBottom: theme.spacing(1),
>           border: '1px dashed red'
> ```

Coloured borders:question: 
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 234 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU65uY6jSrHWj4REjn:-NbU65uY6jSrHWj4REjo:bb73xfv) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/pages/teacherDashboard/YourSchool.tsx#L234)):*
> ```XML
>       <Page.Section
>         sx={{
>           border: '1px dashed orange',
> ```

Same
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 243 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU6IgY4xJu02I4Txrh:-NbU6IgY4xJu02I4Txri:bb73xfv) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/pages/teacherDashboard/YourSchool.tsx#L243)):*
> ```XML
>       <Page.Section
>         sx={{
>           border: '1px dashed lime',
> ```

Same

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138)* status: 1 of 6 files reviewed, 6 unresolved discussions (waiting on @cewei8483)

___
*[`frontend/src/components/Introduction.tsx` line 28 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU9Wh_8fvnP02OapT7:-NbVcrVD8yIdrLUdsn8l:bo2mplk) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/components/Introduction.tsx#L28)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Is this about the alignment issue?
</blockquote></details>

This got caried over from another PR, removed 
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 147 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU5AWkC9p8EUqfrKN4:-NbULwUL317PE6VKtkN0:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/pages/teacherDashboard/YourSchool.tsx#L147)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

ESlint complaint: `Expected newline between test and consequent of ternary expressio` [multiline-ternary](https://eslint.org/docs/latest/rules/multiline-ternary)
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 214 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU79wMDzlU4wNi77d4:-NbVcaFnCNGzAmFFXUQM:b-9o2qhu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/pages/teacherDashboard/YourSchool.tsx#L214)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

See review discussion
</blockquote></details>

I tried to make it as close as possible to the production site. Is the code too cluttered? If so I can remove it :) 
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 217 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU5xKsCZdmV_5raUsT:-NbULhfgBs-sq5DCoijl:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/pages/teacherDashboard/YourSchool.tsx#L217)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Coloured borders:question: 
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 234 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU65uY6jSrHWj4REjn:-NbULhGt1z7w0ABt7oMF:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/pages/teacherDashboard/YourSchool.tsx#L234)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 243 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU6IgY4xJu02I4Txrh:-NbULiMvCMx5oGp_5tzT:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/pages/teacherDashboard/YourSchool.tsx#L243)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.

**Review by cewei8483 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @KamilPawel)

___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 214 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU79wMDzlU4wNi77d4:-NbYpNYL-0ecU11DwchE:bad1zra) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/pages/teacherDashboard/YourSchool.tsx#L214)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

I tried to make it as close as possible to the production site. Is the code too cluttered? If so I can remove it :) 
</blockquote></details>

A little bit for me, but it's fine.
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 240 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbYntcO2PiIhABFDdKD:-NbYntcO2PiIhABFDdKE:b-kg7fee) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10622a07b447bc8eaff0b5fc53da18a1da6c5b55/frontend/src/pages/teacherDashboard/YourSchool.tsx#L240)):*
> ```XML
>       <Page.Section
>         sx={{
>           marginTop: theme.spacing(2),
> ```

Just nitpicking - any particular reason to use marginTop here instead of paddingTop like you did to the other two page sections? If not it would be better to use the same attribute.

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @cewei8483)

___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 214 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbU79wMDzlU4wNi77d4:-NbZwueeET-KQvKjgnpl:b32wtd) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/bddc06187a74979730059d5652c18113fbb06d04/frontend/src/pages/teacherDashboard/YourSchool.tsx#L214)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

A little bit for me, but it's fine.
</blockquote></details>

ok
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 240 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-NbYntcO2PiIhABFDdKD:-NbZwlqI8kfpS8YRBQTq:bf4r688) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10622a07b447bc8eaff0b5fc53da18a1da6c5b55/frontend/src/pages/teacherDashboard/YourSchool.tsx#L240)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Just nitpicking - any particular reason to use marginTop here instead of paddingTop like you did to the other two page sections? If not it would be better to use the same attribute.
</blockquote></details>

for padding I needed a larger number, while margin comes in larger increments

**Review by cewei8483 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/138#-:-Nb_-jVd1TxlFHe0Eykr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Comment by KamilPawel** [comment]
https://development-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/school

**Pull request merged**
