### PR TITLE
feat: teacher teach delete class

### PR DESCRIPTION
**Pull request by cewei8483**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/183)

### CODE REVIEW

**Comment by cewei8483** [comment]
TODO: needs to fetch data from API to check if there're still students in a class

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/183)* status: all files reviewed, 1 unresolved discussion (waiting on @cewei8483)

___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 360 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/183#-Nfz2f3646wSpt18IRmB:-Nfz2f3646wSpt18IRmC:b-17i0m0) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/da7d97fa2f79cfcc7898d47192ac216679501c9f/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L360)):*
> ```XML
>             }
>           });
>           navigate(0);
> ```

why 2 navigate functions?

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/183)* status: all files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 360 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/183#-Nfz2f3646wSpt18IRmB:-NfzIEdt1OKR70-dh9Vs:b-3tgol5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/da7d97fa2f79cfcc7898d47192ac216679501c9f/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L360)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

why 2 navigate functions?
</blockquote></details>

`navigate(0)` is to refresh the page

**Review by KamilPawel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/183)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Review by KamilPawel — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/183)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Pull request merged**
