### PR TITLE
Student management pages

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45)

### CODE REVIEW

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 11 of 23 files at r1, 5 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45)* status: 16 of 23 files reviewed, 16 unresolved discussions (waiting on @faucomte97)

___
*[`frontend/src/app/router.tsx` line 45 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpQoAXBGReXDKcPekd:-NXpQoAXBGReXDKcPeke:b-t6mk84) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/app/router.tsx#L45)):*
> ```XML
>         editClass: _('&accessCode={accessCode}', {
>           additional: _('&setView=additional'),
>           editStudent: _('&studentID={studentID}'),
> ```

rename studentID to studentId as is in EditClasses.tsx
___
*[`frontend/src/app/router.tsx` line 48 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpQffe4eteGBJb9dZR:-NXpQffe4eteGBJb9dZS:b-o934w) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/app/router.tsx#L48)):*
> ```XML
>           resetStudents: _('&setView=reset'),
>           moveStudents: _('&setView=move'),
>           releaseStudents: _('setView=release')
> ```

rename setView to view as is in EditClasses.tsx
___
*[`frontend/src/components/form/StudentNameField.tsx` line 4 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpOamU4Iy_x0rLLy-Q:-NXpOamU4Iy_x0rLLy-R:b-b0utdz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/components/form/StudentNameField.tsx#L4)):*
> ```XML
> import { InputAdornment } from '@mui/material';
> import { PersonOutlined } from '@mui/icons-material';
> import { TextField } from 'codeforlife/lib/esm/components/form';
> ```

import TextFieldProps
___
*[`frontend/src/components/form/StudentNameField.tsx` line 7 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpOfCMDJMpZ7Zh8DaD:-NXpOfCMDJMpZ7Zh8DaE:baaknzq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/components/form/StudentNameField.tsx#L7)):*
> ```XML
> import * as Yup from 'yup';
> 
> const StudentNameField: React.FC<{
> ```

extend TextFieldProps with custom props. something like: "TextFieldProps & { readOnly?: boolean; style?: CSSProperties;  }"
___
*[`frontend/src/components/form/StudentNameField.tsx` line 16 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpPEM79KGE0a3BiN_S:-NXpPEM79KGE0a3BiN_T:b-ct1jw7) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/components/form/StudentNameField.tsx#L16)):*
> ```XML
>   helperText = 'Choose a name',
>   readOnly = false,
>   style = undefined
> ```

remove "= undefined". will be undefined by default
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 144 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpRQZIEXvZakobWXYS:-NXpRQZIEXvZakobWXYT:b-2bhe7g) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L144)):*
> ```XML
> }) => {
>     const params = SearchParams.get<{
>       view?: string;
> ```

set type to be an array of options
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 145 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpRBnM5zw5_H-Jvrm2:-NXpRBnM5zw5_H-Jvrm3:bwu7721) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L145)):*
> ```XML
>     const params = SearchParams.get<{
>       view?: string;
>       studentID?: number;
> ```

careful with typos. make it studentId like below.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 148 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpRMFE02Yj53mc-Fyx:-NXpRMFE02Yj53mc-Fyy:b-ilqc5u) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L148)):*
> ```XML
>     }>({
>       view: {
>         isRequired: false
> ```

add validation for the different options
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 150 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpRfQU26_-YRjcsu_o:-NXpRfQU26_-YRjcsu_p:b-c05hzi) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L150)):*
> ```XML
>         isRequired: false
>       },
>       studentId: {
> ```

cast to Number. Remember all search params are strings by default
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx` line 68 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpb9lmE9einq0MHY2v:-NXpb9lmE9einq0MHY2w:be3c920) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx#L68)):*
> ```XML
> 
> const EditStudent: React.FC<{
>   accessCode: string;
> ```

pass in selected student and render accordingly below
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/moveStudent/MoveStudent.tsx` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpayfr0nH6C8m9iTDX:-NXpayfr0nH6C8m9iTDY:bkfko08) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/moveStudent/MoveStudent.tsx#L10)):*
> ```XML
> 
> const SelectClassForm: React.FC<{
>   setNewClassSelected: (newClassName: string) => void,
> ```

pass in selected students and map them below when rendering 
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpavazD8heVjzte183:-NXpavazD8heVjzte184:bkfko08) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx#L10)):*
> ```XML
> 
> const ReleaseStudentsForm: React.FC<{
>   studentNames: string[],
> ```

pass in selected students and map them below when rendering 
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx` line 30 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpU0c4ClKdqVrrXMJ8:-NXpU0c4ClKdqVrrXMJ9:bhtxqcx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx#L30)):*
> ```XML
>           <>
>             <Grid item sm={6}>
>               <StudentNameField
> ```

give unique name names to each field (including email fields)
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx` line 49 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpUQNeCyfS24QL7fJ9:-NXpUQNeCyfS24QL7fJA:b-q0di2t) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx#L49)):*
> ```XML
>             {/* TODO: Replace with proper margin */}
>             <Grid item sm={6} sx={{ mb: '40px' }}>
>               <EmailField
> ```

missing validation to check if it matches new email address field. see how I handle this with [confirming new passwords](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/23987527963f5f3e4f8046991c0b2e9d8bdef6c3/src/components/form/NewPasswordField.tsx#LL79C6-L79C6). it can be tricky.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx` line 78 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpamIbBuqu3NRcZUfJ:-NXpamIbBuqu3NRcZUfK:bkfko08) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx#L78)):*
> ```XML
> 
> const ReleaseStudent: React.FC<{
>   accessCode: string;
> ```

pass in selected students and map them below when rendering 
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/resetStudent/ResetStudent.tsx` line 8 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpa_w89vJCxxScUyBE:-NXpa_w89vJCxxScUyBF:bkfko08) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/resetStudent/ResetStudent.tsx#L8)):*
> ```XML
> 
> const ResetStudent: React.FC<{
>   accessCode: string;
> ```

pass in selected students and map them below when rendering

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45)* status: 16 of 23 files reviewed, 17 unresolved discussions (waiting on @faucomte97)

___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx` line 114 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpdi-GCFLusdu86dfb:-NXpdi-GCFLusdu86dfc:b3b33lz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx#L114)):*
> ```XML
>       </Typography>
>       <Typography>
>         The students will then log in with their email via the <a href={paths.login.independent._}>independent student login</a>. Their passwords will stay
> ```

use link component with className='body'

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45)* status: 16 of 23 files reviewed, 17 unresolved discussions (waiting on @faucomte97 and @SKairinos)

___
*[`frontend/src/app/router.tsx` line 45 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpQoAXBGReXDKcPekd:-NXtGQ6k6wOUm9loeVdJ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/app/router.tsx#L45)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename studentID to studentId as is in EditClasses.tsx
</blockquote></details>

Done.
___
*[`frontend/src/app/router.tsx` line 48 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpQffe4eteGBJb9dZR:-NXtGafF64Qi-nHGr6FP:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/app/router.tsx#L48)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

rename setView to view as is in EditClasses.tsx
</blockquote></details>

Done.
___
*[`frontend/src/components/form/StudentNameField.tsx` line 4 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpOamU4Iy_x0rLLy-Q:-NXtHFDN-2PEodFhoyXH:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/components/form/StudentNameField.tsx#L4)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

import TextFieldProps
</blockquote></details>

Done.
___
*[`frontend/src/components/form/StudentNameField.tsx` line 7 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpOfCMDJMpZ7Zh8DaD:-NXtHFpP2yvuU6Azr4p8:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/components/form/StudentNameField.tsx#L7)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

extend TextFieldProps with custom props. something like: "TextFieldProps & { readOnly?: boolean; style?: CSSProperties;  }"
</blockquote></details>

Done.
___
*[`frontend/src/components/form/StudentNameField.tsx` line 16 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpPEM79KGE0a3BiN_S:-NXtGpNv6_Ocu-wzHoHi:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/components/form/StudentNameField.tsx#L16)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

remove "= undefined". will be undefined by default
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 144 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpRQZIEXvZakobWXYS:-NXtIE0X5u1Y0Z6p_3vK:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L144)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

set type to be an array of options
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 145 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpRBnM5zw5_H-Jvrm2:-NXtHJcLC8-Ug9V553o0:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L145)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

careful with typos. make it studentId like below.
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 148 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpRMFE02Yj53mc-Fyx:-NXtJ8Hj6ZxowfnBLoEG:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L148)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

add validation for the different options
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 150 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpRfQU26_-YRjcsu_o:-NXtJAlxD993057uYmc_:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L150)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

cast to Number. Remember all search params are strings by default
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx` line 68 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpb9lmE9einq0MHY2v:-NXtN9bt7SWai6neYvVF:b-kr7igk) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/editStudent/EditStudent.tsx#L68)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

pass in selected student and render accordingly below
</blockquote></details>

Passed it in and added a TODO to gather data from it
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/moveStudent/MoveStudent.tsx` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpayfr0nH6C8m9iTDX:-NXyjec26EuMRWUGd4NC:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/moveStudent/MoveStudent.tsx#L10)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

pass in selected students and map them below when rendering 
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpavazD8heVjzte183:-NXyjodl567PloAWIHOK:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx#L10)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

pass in selected students and map them below when rendering 
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx` line 30 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpU0c4ClKdqVrrXMJ8:-NXylNyJ-hLfaTH5RZy7:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx#L30)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

give unique name names to each field (including email fields)
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx` line 49 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpUQNeCyfS24QL7fJ9:-NY2iRRTDPyBslkPAZZy:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx#L49)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

missing validation to check if it matches new email address field. see how I handle this with [confirming new passwords](https://github.com/ocadotechnology/codeforlife-package-javascript/blob/23987527963f5f3e4f8046991c0b2e9d8bdef6c3/src/components/form/NewPasswordField.tsx#LL79C6-L79C6). it can be tricky.
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx` line 78 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpamIbBuqu3NRcZUfJ:-NXzTIJ8D_2GR2_GnzI3:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx#L78)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

pass in selected students and map them below when rendering 
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx` line 114 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpdi-GCFLusdu86dfb:-NXzYM730UGLTdrxUBWw:b-v5114k) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/releaseStudent/ReleaseStudent.tsx#L114)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use link component with className='body'
</blockquote></details>

Done. But it makes the text bold on hover - has this been fixed?
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/student/resetStudent/ResetStudent.tsx` line 8 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45#-NXpa_w89vJCxxScUyBE:-NXzYWfF-Axby8BtO0go:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e885e153e37f2bbb3571b35b3ca5d38ac7b63e88/frontend/src/pages/teacherDashboard/classes/editClass/student/resetStudent/ResetStudent.tsx#L8)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

pass in selected students and map them below when rendering 
</blockquote></details>

Done.

**Review by SKairinos — APPROVED** [review]
> Reviewed 6 of 8 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
