### PR TITLE
feat: dotmailer views

### PR DESCRIPTION
**Pull request by cewei8483**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69)

### CODE REVIEW

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> Reviewed 11 of 82 files at r1, 69 of 69 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69)* status: 80 of 82 files reviewed, 8 unresolved discussions (waiting on @cewei8483)

___
*[`backend/Pipfile` line 39 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzEHJmEjUWy2EIL9J7:-NZzEHJmEjUWy2EIL9J8:ba9imkz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/Pipfile#L39)):*
> ```TOML
> google-cloud-container = "==2.3.0"
> "django-anymail[amazon_ses]" = "==7.0.*"
> django-cors-headers = "*"
> ```

Use pip freeze to get the current version of django-cors-headers and set it to that version :)
___
*[`backend/portal/views/dotmailer.py` line 16 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzEZvu0KqX-0i60tre:-NZzEZvu0KqX-0i60trf:b-am51l7) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/portal/views/dotmailer.py#L16)):*
> ```Python
> import json
> 
> @csrf_exempt
> ```

I do think it is easier to disable csrf in settings rather than for every view?
___
*[`backend/portal/views/dotmailer.py` line 24 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzEf--EWMMAYCt1GaK:-NZzEf--EWMMAYCt1GaL:buh9vzc) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/portal/views/dotmailer.py#L24)):*
> ```Python
>             validate_email(user_email)
>         except ValidationError:
>             return JsonResponse(status=200, data={'success': False})
> ```

If validation is false should possible return a bad request; code 400?
___
*[`backend/portal/views/dotmailer.py` line 32 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzEcV_EIMgDA193biO:-NZzEcV_EIMgDA193biP:brhumzf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/portal/views/dotmailer.py#L32)):*
> ```Python
> 
> 
> @csrf_exempt
> ```

Same here 
___
*[`backend/portal/views/dotmailer.py` line 48 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzEzOMEQBNhf_WgBa7:-NZzEzOMEQBNhf_WgBa8:bfezsih) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/portal/views/dotmailer.py#L48)):*
> ```Python
>             return JsonResponse(status=200, data={'success': True})
>         
>     return HttpResponse(status=405)
> ```

New empty line at the end of the file 
___
*[`backend/service/settings.py` line 72 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzFDNH-V5X4fYUnatf:-NZzFDNH-V5X4fYUnatg:b-ipj47f) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/service/settings.py#L72)):*
> ```Python
>     "corsheaders.middleware.CorsMiddleware",
>     "django.middleware.common.CommonMiddleware",
>     "django.middleware.csrf.CsrfViewMiddleware",
> ```

if you comment this out, it will disable csrf



_Code quote:_
```Python
 "django.middleware.csrf.CsrfViewMiddleware",
```
___
*[`frontend/src/app/api.ts` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzFJjq6qZgpDUwicBu:-NZzFJjq6qZgpDUwicBv:bwnp3v6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/a60aa4b1f7f436639415d743e6030acee5d73bbb/frontend/src/app/api.ts#L10)):*
> ```XML
>   FetchBaseQueryError
> } from '@reduxjs/toolkit/query';
> import { useNavigate } from 'react-router-dom';
> ```

Why did you remove it and used window object?
___
*[`frontend/src/features/footer/SignUp.tsx` line 41 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzF_Xq6yYHnX2L52pD:-NZzF_Xq6yYHnX2L52pE:bcmea9y) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/frontend/src/features/footer/SignUp.tsx#L41)):*
> ```XML
> 
>   const handleSubmit = (values: SignUpValues, { setSubmitting }: FormikHelpers<SignUpValues>): void => {
>     setSubmitting(false);
> ```

setSubmitting should be done if the request fails, so in the catch block. Otherwise if we submit and something goes wrong and the form in some way relies on this, the user will not be able to submit

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69)* status: 80 of 82 files reviewed, 9 unresolved discussions (waiting on @cewei8483)

___
*[`frontend/src/app/api.ts` line 15 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzXAG22mYPEBPzj7k8:-NZzXAG22mYPEBPzj7k9:b8r4rkt) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/frontend/src/app/api.ts#L15)):*
> ```XML
> const baseQuery = fetchBaseQuery({
>   // baseUrl: process.env.REACT_APP_API_BASE_URL
>   baseUrl: 'http://localhost:8000/'
> ```

Should ideally overwrite value in the .env file :thinking: 



_Code quote:_
```XML
  // baseUrl: process.env.REACT_APP_API_BASE_URL
  baseUrl: 'http://localhost:8000/'
```

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69)* status: 77 of 82 files reviewed, 9 unresolved discussions (waiting on @KamilPawel)

___
*[`backend/Pipfile` line 39 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzEHJmEjUWy2EIL9J7:-NZzfcEw70DhMa9NEdLg:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/Pipfile#L39)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Use pip freeze to get the current version of django-cors-headers and set it to that version :)
</blockquote></details>

Done.
___
*[`backend/portal/views/dotmailer.py` line 16 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzEZvu0KqX-0i60tre:-NZzfh13CIH4xel4PlqP:boojm6k) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/portal/views/dotmailer.py#L16)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

I do think it is easier to disable csrf in settings rather than for every view?
</blockquote></details>

This one is there in the old repo so I'll keep it.
___
*[`backend/portal/views/dotmailer.py` line 24 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzEf--EWMMAYCt1GaK:-NZzgLH62TQ7m51ZqhuC:b-6jbygp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/portal/views/dotmailer.py#L24)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

If validation is false should possible return a bad request; code 400?
</blockquote></details>

If the BE returns 400 it will be redirected to error pages, which is not our intended behaviour.
___
*[`backend/portal/views/dotmailer.py` line 32 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzEcV_EIMgDA193biO:-NZzfrqv7mBDij3B-LKI:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/portal/views/dotmailer.py#L32)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Same here 
</blockquote></details>

Done.
___
*[`backend/portal/views/dotmailer.py` line 48 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzEzOMEQBNhf_WgBa7:-NZzgcjCAkwhZgpvOwmK:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/portal/views/dotmailer.py#L48)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

New empty line at the end of the file 
</blockquote></details>

Done.
___
*[`backend/service/settings.py` line 72 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzFDNH-V5X4fYUnatf:-NZzgnzBCAoH73amVLIm:b-9ujs53) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/service/settings.py#L72)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

if you comment this out, it will disable csrf
</blockquote></details>

Got it. But I think we should keep it enabled on main branch?
___
*[`frontend/src/app/api.ts` line 10 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzFJjq6qZgpDUwicBu:-NZzh9vg26Z6mJQvMlSF:b6jw1l5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/a60aa4b1f7f436639415d743e6030acee5d73bbb/frontend/src/app/api.ts#L10)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Why did you remove it and used window object?
</blockquote></details>

If you use hook inside this, it will complain about `Invalid hook call` since RTK query is already using hook to wrap it up. I discussed with Stefan the other day about this and he suggested using window object to avoid hook.
___
*[`frontend/src/app/api.ts` line 15 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzXAG22mYPEBPzj7k8:-NZzhFx_17sMvafrNTyF:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/frontend/src/app/api.ts#L15)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Should ideally overwrite value in the .env file :thinking: 
</blockquote></details>

Done.
___
*[`frontend/src/features/footer/SignUp.tsx` line 41 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzF_Xq6yYHnX2L52pD:-NZziEgp9tsQ8F1NhDo2:b-3pb7ty) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/frontend/src/features/footer/SignUp.tsx#L41)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

setSubmitting should be done if the request fails, so in the catch block. Otherwise if we submit and something goes wrong and the form in some way relies on this, the user will not be able to submit
</blockquote></details>

I thought once the form is submitted, isSubmitted should be set to false?

**Review by KamilPawel — APPROVED** [review]
> Reviewed 2 of 82 files at r1, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69)* status: 80 of 82 files reviewed, 1 unresolved discussion (waiting on @cewei8483)

___
*[`backend/service/settings.py` line 72 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzFDNH-V5X4fYUnatf:-NZzkUJxDA6YB3gc4i3k:b877ypk) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/backend/service/settings.py#L72)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Got it. But I think we should keep it enabled on main branch?
</blockquote></details>

Yea for dev purposes :) 
___
*[`frontend/src/features/footer/SignUp.tsx` line 41 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzF_Xq6yYHnX2L52pD:-NZzn_bd3yiBl8hYjbvR:b6k2rh2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/frontend/src/features/footer/SignUp.tsx#L41)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

I thought once the form is submitted, isSubmitted should be set to false?
</blockquote></details>

I was thinking that once the submission is done, then you would set submission to false right ?

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69)* status: 80 of 82 files reviewed, 1 unresolved discussion (waiting on @cewei8483)

___
*[`frontend/src/app/api.ts` line 15 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-NZzXAG22mYPEBPzj7k8:-NZzoxdyEein5OGVpXYm:b4c9lyr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f60bdf47dfb82fc1e957ef8bcee974fe34657716/frontend/src/app/api.ts#L15)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:thumbsup:

**Review by KamilPawel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-:-N_8DOvj9XeCAHNdnwXF:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @cewei8483)

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @cewei8483)

___
*[`frontend/src/app/api.ts` line 49 at r5](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-N_8GgR0-TkzFpkeA0lp:-N_8GgR0-TkzFpkeA0lq:b8683d6) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/a11dc7bd422d4c55197c851c1f590d8101c2f314/frontend/src/app/api.ts#L49)):*
> ```XML
>         url: 'news_signup/',
>         method: 'POST',
>         body: payload
> ```

Did we say we are going with JSON or QS encoding?

**Review by KamilPawel — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/69#-:-N_8StNqD5XNWAGOGGkB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @cewei8483)

**Pull request merged**
