### PR TITLE
feat: adding get-students-endpoint

### PR DESCRIPTION
**Pull request by KamilPawel**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184)

### CODE REVIEW

**Review by cewei8483 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @KamilPawel)

___
*[`backend/portal/views/teacher/dashboard.py` line 83 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184#-Nfl0_sQ3Nv7mOdeSmJQ:-Nfl0_sQ3Nv7mOdeSmJR:b-3nfnep) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/471f8f56b98d44a813403a0991587191754dd0b2/backend/portal/views/teacher/dashboard.py#L83)):*
> ```Python
>             }
>             if student.new_user
>             else "",
> ```

Is there any chance that student.new_user is null?
If not remove the condition, and even if really so, returning empty data with same structure would be better,
e.g. 
```
{
    "id": "",
    "first_name": "",
    "last_name": "",
}
 ```
___
*[`backend/portal/views/teacher/dashboard.py` line 89 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184#-Nfl1KO1Dxb80xeSjEXO:-Nfl1KO1Dxb80xeSjEXP:b-vbpn47) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/471f8f56b98d44a813403a0991587191754dd0b2/backend/portal/views/teacher/dashboard.py#L89)):*
> ```Python
>             "blocked_time": student.blocked_time.strftime("%Y-%m-%d %H:%M:%S")
>             if student.blocked_time
>             else "",
> ```

same here (concerning the data type)

**Review by cewei8483 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @KamilPawel)

___
*[`frontend/src/app/api/teacher/teach.ts` line 38 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184#-Nfl1tGA1ixFRXX7aTR3:-Nfl1tGA1ixFRXX7aTR4:bpd2r8r) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/471f8f56b98d44a813403a0991587191754dd0b2/frontend/src/app/api/teacher/teach.ts#L38)):*
> ```XML
>             lastName: string;
>           };
>           pendingClassRequest: any;
> ```

Try not to use any here :joy:

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @cewei8483)

___
*[`backend/portal/views/teacher/dashboard.py` line 76 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184#-Nfl2LLY8R4QFyz_47Rw:-Nfl7vIh3zXn5o5j0co9:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/471f8f56b98d44a813403a0991587191754dd0b2/backend/portal/views/teacher/dashboard.py#L76)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Either change the field to a number or change the type to string in the FE since this field is specified as number there
</blockquote></details>

Done.
___
*[`backend/portal/views/teacher/dashboard.py` line 83 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184#-Nfl0_sQ3Nv7mOdeSmJQ:-Nfl6nQL6zHKFvpU7-oK:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/471f8f56b98d44a813403a0991587191754dd0b2/backend/portal/views/teacher/dashboard.py#L83)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Is there any chance that student.new_user is null?
If not remove the condition, and even if really so, returning empty data with same structure would be better,
e.g. 
```
{
    "id": "",
    "first_name": "",
    "last_name": "",
}
 ```
</blockquote></details>

Done.
___
*[`backend/portal/views/teacher/dashboard.py` line 89 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184#-Nfl1KO1Dxb80xeSjEXO:-Nfl6n74A1WwaEgKXqEA:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/471f8f56b98d44a813403a0991587191754dd0b2/backend/portal/views/teacher/dashboard.py#L89)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

same here (concerning the data type)
</blockquote></details>

Done.
___
*[`frontend/src/app/api/teacher/teach.ts` line 38 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184#-Nfl1tGA1ixFRXX7aTR3:-Nfl513ZDXjeq6yh_Fx4:b32x0x) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/471f8f56b98d44a813403a0991587191754dd0b2/frontend/src/app/api/teacher/teach.ts#L38)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Try not to use any here :joy:
</blockquote></details>

xd

**Review by cewei8483 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184#-:-NflB9zxCapCh0XMFM2z:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved

**Review by cewei8483 — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Pull request merged**
