### PR TITLE
fix: padding and default ticked levels

### PR DESCRIPTION
**Pull request by KamilPawel**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126)

### CODE REVIEW

**Review by cewei8483 — CHANGES_REQUESTED** [review]
Could you also add marginTop={theme.spacing(3)} to `Save level settings` button and the `Transfer class` one as you did in the `External requests setting` section? 
Laura thinks they are a little bit too close to the texts.

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126#-:-Navmixr4kI2csPVJp0r:b-s77uc0)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @KamilPawel)

___
*[`frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx` line 294 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126#-NavkQm36PmLyRpDSQL2:-NavkQm36PmLyRpDSQL3:b-tgdcmp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4caa2cb822ae29c96db33b6dce1fd1555f31a25a/frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx#L294)):*
> ```XML
>       <Page.Section
>         sx={{
>           my: theme.spacing(3)
> ```

Stefan and I had already worked on the page section padding issue. So you don't need to add margins again.

See: https://github.com/ocadotechnology/codeforlife-package-javascript/commit/a87bc5f01934864dc8c2e774f7cbb48ce4ecba30#diff-4fd75e935e9b57d0aea179c6263ab8222016170969be262ea49a404d24e3e5ce
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx` line 312 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126#-NavlewH-BX9I24Fc255:-NavlewI0S57u9ySZAMu:b3n86wj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4caa2cb822ae29c96db33b6dce1fd1555f31a25a/frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx#L312)):*
> ```XML
>       <Page.Section
>         sx={{ my: theme.spacing(2) }}
>         gridProps={{ bgcolor: theme.palette.info.light }}
> ```

Do we need to change this to info.light?
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx` line 322 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126#-Navm4WQBbKhyB8dV1m2:-Navm4WQBbKhyB8dV1m3:b45pteh) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4caa2cb822ae29c96db33b6dce1fd1555f31a25a/frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx#L322)):*
> ```XML
>       <Page.Section
>         sx={{
>           marginTop: theme.spacing(3.2),
> ```

theme.spacing is using 8px as its base. I think keep the value to integer or .5 would be better.

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @cewei8483)

___
*[`frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx` line 294 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126#-NavkQm36PmLyRpDSQL2:-NbF5vmGA4tEgYbS6D2E:b-x7cv6t) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4caa2cb822ae29c96db33b6dce1fd1555f31a25a/frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx#L294)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Stefan and I had already worked on the page section padding issue. So you don't need to add margins again.

See: https://github.com/ocadotechnology/codeforlife-package-javascript/commit/a87bc5f01934864dc8c2e774f7cbb48ce4ecba30#diff-4fd75e935e9b57d0aea179c6263ab8222016170969be262ea49a404d24e3e5ce
</blockquote></details>

I will remove the padding then 
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx` line 312 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126#-NavlewH-BX9I24Fc255:-NbF-weY952WsMSQhWFX:bu3oq93) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4caa2cb822ae29c96db33b6dce1fd1555f31a25a/frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx#L312)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Do we need to change this to info.light?
</blockquote></details>

This was the colour of the grey on the tables no? 
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx` line 322 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126#-Navm4WQBbKhyB8dV1m2:-NbF-urt-MfbXj1lD38l:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4caa2cb822ae29c96db33b6dce1fd1555f31a25a/frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx#L322)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

theme.spacing is using 8px as its base. I think keep the value to integer or .5 would be better.
</blockquote></details>

Done.

**Review by cewei8483 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[`frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx` line 312 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126#-NavlewH-BX9I24Fc255:-NbF0CTjB5qUtevnicU2:bn7tyvm) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4caa2cb822ae29c96db33b6dce1fd1555f31a25a/frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx#L312)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

This was the colour of the grey on the tables no? 
</blockquote></details>

There is no related requirement in [this issue](https://app.zenhub.com/workspaces/code-for-life-development--56f2afba6e54555c586f6db3/issues/gh/ocadotechnology/codeforlife-portal-react/96). Besides by `table grey` Laura means adjusting the table color in new portal to the exact same one used in the current site (which I have already done).

**Review by cewei8483 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[`frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx` line 312 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126#-NavlewH-BX9I24Fc255:-NbFnq8009kG21NytI9X:bgtoqvq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4caa2cb822ae29c96db33b6dce1fd1555f31a25a/frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx#L312)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Reverted
</blockquote></details>

Now it becomes white:sweat_smile: 
It should be `bgcolor: theme.palette.info.main` as it was.

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @cewei8483)

___
*[`frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx` line 312 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126#-NavlewH-BX9I24Fc255:-NbH3vDf0X6ney4ml81Q:brybf96) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/4caa2cb822ae29c96db33b6dce1fd1555f31a25a/frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx#L312)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Now it becomes white:sweat_smile: 
It should be `bgcolor: theme.palette.info.main` as it was.
</blockquote></details>

Sorry :sob:

**Review by cewei8483 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/126#-:-NbJYKLxC8LZFVdVFPIx:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Pull request merged**
