### PR TITLE
fix: update password

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/314)

### CODE REVIEW

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 6 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/314)* status: 6 of 12 files reviewed, all discussions resolved

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/314)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/tests/serializers/test_user.py` line 301 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/314#-NtQj-N08bA08t5hgpaO:-NtQj-N08bA08t5hgpaP:bkwx3h3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0a0e8acff72d3e919ccd1d63b1cc1e1e003851f1/backend/api/tests/serializers/test_user.py#L301)):*
> ```Python
> 
>     def test_validate_token__does_not_match(self):
>         """Cannot validate the token of a user that does not exist."""
> ```

Update docstring
___
*[`backend/api/tests/views/test_user.py` line 186 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/314#-NtQjHrA2iTrM1JgoMNf:-NtQjHrA2iTrM1JgoMNg:bkm2ay3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0a0e8acff72d3e919ccd1d63b1cc1e1e003851f1/backend/api/tests/views/test_user.py#L186)):*
> ```Python
>     def test_get_queryset__reset_password(self):
>         """
>         Resetting a password can only target the user's whose password is being
> ```

the user*

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/314#-:-NtVm-kOBcNH2bz9NBsl:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/314)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

___
*[`backend/api/tests/serializers/test_user.py` line 301 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/314#-NtQj-N08bA08t5hgpaO:-NtVkY0G79XS3449aOhK:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0a0e8acff72d3e919ccd1d63b1cc1e1e003851f1/backend/api/tests/serializers/test_user.py#L301)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Update docstring
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_user.py` line 186 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/314#-NtQjHrA2iTrM1JgoMNf:-NtVknzH-Rwb2Z2-luLw:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0a0e8acff72d3e919ccd1d63b1cc1e1e003851f1/backend/api/tests/views/test_user.py#L186)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

the user*
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/314)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
