### PR TITLE
2094 fix component styles

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/43)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 40 of 40 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/43)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`frontend/src/features/header/Header.tsx` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/43#-NXLjbpW1EN23Y9MWQNU:-NXLjbpX37dI-oWd0nEL:b-ikza4f) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/da061476a7b38fab3980fb33a5887b550380a634/frontend/src/features/header/Header.tsx#L31)):*
> ```XML
>     color: '#383b3b',
>     fontSize: '27.5px',
>     marginLeft: extraMargin
> ```

Do these props need to be defined here or can we reuse the values specified from the theme?



_Code quote:_
```XML
  const extraMargin = '10px';
  const linkProps: LinkProps = {
    display: { xs: 'none', md: 'inline' },
    color: '#383b3b',
    fontSize: '27.5px',
    marginLeft: extraMargin
```
___
*[`frontend/src/features/header/LoginSelect.tsx` line 101 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/43#-NXLk74q7h4I-ZUzjHN9:-NXLk74q7h4I-ZUzjHNA:bcee54u) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/da061476a7b38fab3980fb33a5887b550380a634/frontend/src/features/header/LoginSelect.tsx#L101)):*
> ```XML
>         Log in
>       </MenuItem>
>       <LoginMenuItem
> ```

Order here needs to be teacher, student then independent

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/43)* status: 47 of 51 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`frontend/src/features/header/Header.tsx` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/43#-NXLjbpW1EN23Y9MWQNU:-NXR1RO20Snl_lITOxJX:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/da061476a7b38fab3980fb33a5887b550380a634/frontend/src/features/header/Header.tsx#L31)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do these props need to be defined here or can we reuse the values specified from the theme?
</blockquote></details>

Done.
___
*[`frontend/src/features/header/LoginSelect.tsx` line 101 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/43#-NXLk74q7h4I-ZUzjHN9:-NXQQaXo4vYJoAmMqQHR:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/da061476a7b38fab3980fb33a5887b550380a634/frontend/src/features/header/LoginSelect.tsx#L101)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Order here needs to be teacher, student then independent
</blockquote></details>

Done.

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/43)* status: 58 of 60 files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`frontend/public/index.html` line 60 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/43#-NXV_eNG9RPN92VqBKK9:-NXVgY-bBHAgBhz4Peca:bj67okr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07ce9d9b51575b3cdaf8a23fbc77719dc4bfbdae/frontend/public/index.html#L60)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Is this commented out because we don't want the constant popup? If so, can we add a TODO above it?
</blockquote></details>

added todo
___
*[`frontend/src/pages/teacherDashboard/classes/studentManagement/additionalClassSettings/AdditionalClassSettings.tsx` line 116 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/43#-NXVdAxh9Gq6wuglYUu9:-NXVg_hOB4Zhr8BEWGDI:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/07ce9d9b51575b3cdaf8a23fbc77719dc4bfbdae/frontend/src/pages/teacherDashboard/classes/studentManagement/additionalClassSettings/AdditionalClassSettings.tsx#L116)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Need to fix the colours
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
