### PR TITLE
Teach views edit class

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/174)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/174)* status: 0 of 20 files reviewed, 1 unresolved discussion

___
*[`frontend/package.json` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/174#-NdoZBhK8cy33ebrOwse:-NdoZBhK8cy33ebrOwsf:bnq1wv5) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d281def9258f350a68a7ff85f0420784f67ee486/frontend/package.json#L31)):*
> ```JSON
>     "@mui/material": "^5.11.12",
>     "@reduxjs/toolkit": "^1.9.3",
>     "codeforlife": "github:ocadotechnology/codeforlife-package-javascript#autocomplete_select_only",
> ```

use official version

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/174)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`frontend/package.json` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/174#-NdoZBhK8cy33ebrOwse:-Ndps3US07GXQC0MYwj4:b2nhswy) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d281def9258f350a68a7ff85f0420784f67ee486/frontend/package.json#L31)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

use official version
</blockquote></details>

Yes
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx` line 317 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/174#-Ndpsydd0iJC1oRkHJ3N:-Ndpsydd0iJC1oRkHJ3O:buv4o85) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/7ed67fb8b7660cad49085e509ae2a10f277c5581/frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx#L317)):*
> ```XML
>           Class details
>         </Typography>
>         <ClassDetailsForm goBack={goBack} />
> ```

Does this remove the go back function?

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/174)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx` line 317 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/174#-Ndpsydd0iJC1oRkHJ3N:-Ne3gDX76PLjHxfYY2Q-:bnn0lh) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/7ed67fb8b7660cad49085e509ae2a10f277c5581/frontend/src/pages/teacherDashboard/classes/editClass/additionalSettings/AdditionalSettings.tsx#L317)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Does this remove the go back function?
</blockquote></details>

no.  it'll still be able to navigate back to the edit class page

**Review by faucomte97 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/174)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/174)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
