### PR TITLE
feat: added 3 tabs on teachers dashboard page

### PR DESCRIPTION
**Pull request by KamilPawel**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29)* status: 7 of 12 files reviewed, 3 unresolved discussions (waiting on @KamilPawel)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NVRd1MD8QU5oMsPBQ3x:-NVRd1MD8QU5oMsPBQ3y:b-rvxa30) (no related file):*
I wasn't able to build and test from this branch for some reason :grimacing: 

___
___
*[`frontend/package-lock.json` line 0 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NVRb9RQDaj2QpIhhGdC:-NVRb9RREeW3JSBq_v33:b7n4fsu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/772e8b48d8c613d3500504d46cc7608819fad02b/frontend/package-lock.json#L0)):*
No package-lock please
___
*[`frontend/src/pages/teacherDashboard/constants.ts` line 241 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NVRc-Go65ejAMXwEEKa:-NVRc-Go65ejAMXwEEKb:bffp4f4) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/772e8b48d8c613d3500504d46cc7608819fad02b/frontend/src/pages/teacherDashboard/constants.ts#L241)):*
> ```XML
>   teacherName: '',
>   isStudentProgressVisibleToOthers: false
> };
> ```

Do we need all these consts for now? Is this because of formik?
If so, is there a better alternative to hardcoding the list of countries? Similar to how we do it in django with a third party library?

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 1 of 4 files at r3, 3 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29)* status: 6 of 20 files reviewed, 2 unresolved discussions (waiting on @KamilPawel)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29)* status: 6 of 20 files reviewed, 17 unresolved discussions (waiting on @KamilPawel)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViAS4EAxOuovUfw0Pt:-NViAS4EAxOuovUfw0Pu:b-ad69kh) (no related file):*
I can't find where the code for it is, but the "Welcome back" header is bigger than it should be

___
___
*[`frontend/src/components/CflTable.tsx` line 75 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViDUTS1SYkeibmSgAb:-NViDUTS1SYkeibmSgAc:b-uolbla) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/components/CflTable.tsx#L75)):*
> ```XML
>   children: React.ReactNode;
> }
> const CflTable: React.FC<CflTableProps> = ({
> ```

The header is black, can you make it grey like we have it currently?
Also the rows are alternating in background colour, is this OK?
___
*[`frontend/src/components/formik/CflAutoComplete.tsx` line 1 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViDOlpAgfJK0AnTR_o:-NViDOlpAgfJK0AnTR_p:b1ylx13) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/components/formik/CflAutoComplete.tsx#L1)):*
> ```XML
> import React from 'react';
> ```

What is this file for?
___
*[`frontend/src/pages/teacherDashboard/TeacherAccount.tsx` line 36 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViChaq-ZsNsOofaX84:-NViChaq-ZsNsOofaX85:b-7kgvgt) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherAccount.tsx#L36)):*
> ```XML
> };
> 
> const YourAccountForm: React.FC = () => {
> ```

Missing icons.
___
*[`frontend/src/pages/teacherDashboard/TeacherAccount.tsx` line 97 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViCzzP-R6QwV83EMtp:-NViCzzP-R6QwV83EMtq:b6mo8eu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherAccount.tsx#L97)):*
> ```XML
> };
> 
> const DeleteAccountForm: React.FC = (): JSX.Element => {
> ```

Missing icon.
___
*[`frontend/src/pages/teacherDashboard/TeacherAccount.tsx` line 132 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViD37E-TMfypuPO9hI:-NViD37E-TMfypuPO9hJ:bhln7al) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherAccount.tsx#L132)):*
> ```XML
>         sx={{ color: theme.palette.info.dark }}
>         formControlLabelProps={{
>           label: 'Remove me from the Code for Life newsletter'
> ```

This label is different to the one we currently have + it's too small
___
*[`frontend/src/pages/teacherDashboard/TeacherAccount.tsx` line 144 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViCWzg0oZ6zykH_iVW:-NViCWzg0oZ6zykH_iVX:b-jbnt1e) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherAccount.tsx#L144)):*
> ```XML
>     <BasePage>
>       <DashboardBanner />
>       <DashboardHeader page="Your account" />
> ```

Too small (should be h4 I guess). How come you're using `DashboardHeader` here but not in the other 2 pages?
___
*[`frontend/src/pages/teacherDashboard/TeacherClasses.tsx` line 23 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViBPCBD09WagzrlEnv:-NViBPCBD09WagzrlEnw:b-ro1b8s) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherClasses.tsx#L23)):*
> ```XML
>   return (
>     <>
>       <Typography align="center" variant="h5">
> ```

Too small (h4?)
___
*[`frontend/src/pages/teacherDashboard/TeacherClasses.tsx` line 55 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViBWscBNPLS7IPzlJf:-NViBWscBNPLS7IPzlJg:b-ps7xoh) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherClasses.tsx#L55)):*
> ```XML
>           </CflTableCellElement>
>           <CflTableCellElement justifyContent="center">
>             <Button color="tertiary" endIcon={<CreateOutlined />}>
> ```

The icon here is outlined when it should be filled in (I'm assuming the issue is the same for all the other Edit buttons)
___
*[`frontend/src/pages/teacherDashboard/TeacherClasses.tsx` line 102 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViBh7G9Wj4qviRLywU:-NViBh7G9Wj4qviRLywV:b-nxddu2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherClasses.tsx#L102)):*
> ```XML
>   return (
>     <>
>       <Typography align="center" variant="h5">
> ```

Too small
___
*[`frontend/src/pages/teacherDashboard/TeacherClasses.tsx` line 118 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViCDHQ8sU6DV3mtFnG:-NViCDHQ8sU6DV3mtFnH:bxvwz2h) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherClasses.tsx#L118)):*
> ```XML
> };
> 
> const CreateNewClassForm: React.FC = (): JSX.Element => {
> ```

Missing icons. Teacher name isn't a dropdown.
The checkbox is white, can we change that? (like the one for delete account?)
___
*[`frontend/src/pages/teacherDashboard/TeacherClasses.tsx` line 151 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViCNqK6AZCQL1Sf0B5:-NViCNqK6AZCQL1Sf0B6:bomayjy) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherClasses.tsx#L151)):*
> ```XML
>         name="isStudentProgressVisibleToOthers"
>         formControlLabelProps={{
>           label: "Allow students to see their classmates' progress?"
> ```

This label is too small
___
*[`frontend/src/pages/teacherDashboard/TeacherClasses.tsx` line 161 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViC4T32NMBY_mTL8F0:-NViC4T32NMBY_mTL8F1:b-62fghu) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherClasses.tsx#L161)):*
> ```XML
>   return (
>     <>
>       <Typography align="center" variant="h5">
> ```

You have 2 headings like this right now, you need to get rid of one of them and make sure the text comes after.
___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 68 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViBFuOAtAwzzcmL9u8:-NViBFuOAtAwzzcmL9u9:b-anll0a) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L68)):*
> ```XML
> };
> 
> const UpdateSchoolDetailsForm: React.FC = (): JSX.Element => {
> ```

Missing icons + the button doesn't become enabled when I put it data
___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 206 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViA_rrDQB_tCHk0LzL:-NViA_rs31TY3JabWVex:beyvxs2) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L206)):*
> ```XML
>       <PageSection>
>         <Typography align="center" variant="h5">
>           Your school: {schoolName}: {accessCode}
> ```

This is too small (probably needs to be a h4) and needs the brackets, and not 2 colons
___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 216 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViAuW_4aMTz857i4QJ:-NViAuW_4aMTz857i4QK:bfipmqe) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L216)):*
> ```XML
>           rights to other teachers.
>         </Typography>
>         <Typography variant="h5">
> ```

The invite teacher form should be before this heading

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 14 of 17 files at r4.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29)* status: all files reviewed, 17 unresolved discussions (waiting on @KamilPawel)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29)* status: all files reviewed, 8 unresolved discussions (waiting on @KamilPawel)

___
*[`frontend/src/components/CflTable.tsx` line 75 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViDUTS1SYkeibmSgAb:-NW1neqw5DSDsdwIWpIH:b-qt8vmf) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/components/CflTable.tsx#L75)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

The header is black, can you make it grey like we have it currently?
Also the rows are alternating in background colour, is this OK?
</blockquote></details>

Question about alternating row colours still stands.
___
*[`frontend/src/pages/teacherDashboard/constants.ts` line 241 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NVRc-Go65ejAMXwEEKa:-NW1n_FKAnYzbuHuMC87:b6yanfz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/772e8b48d8c613d3500504d46cc7608819fad02b/frontend/src/pages/teacherDashboard/constants.ts#L241)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we need all these consts for now? Is this because of formik?
If so, is there a better alternative to hardcoding the list of countries? Similar to how we do it in django with a third party library?
</blockquote></details>

Countries are still there
___
*[`frontend/src/pages/teacherDashboard/TeacherAccount.tsx` line 144 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViCWzg0oZ6zykH_iVW:-NW1mn-ACEkE4ZTm83Ew:b-n4o6wy) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherAccount.tsx#L144)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Too small (should be h4 I guess). How come you're using `DashboardHeader` here but not in the other 2 pages?
</blockquote></details>

Still too small
___
*[`frontend/src/pages/teacherDashboard/TeacherClasses.tsx` line 118 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViCDHQ8sU6DV3mtFnG:-NW1mxPW04dg49IPNC9Q:bvcuahp) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherClasses.tsx#L118)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Missing icons. Teacher name isn't a dropdown.
The checkbox is white, can we change that? (like the one for delete account?)
</blockquote></details>

Teacher name still not a dropdown, checkbox is still white
___
*[`frontend/src/pages/teacherDashboard/TeacherClasses.tsx` line 161 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViC4T32NMBY_mTL8F0:-NW1nBQIDplewrfarmP4:boof3vr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherClasses.tsx#L161)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You have 2 headings like this right now, you need to get rid of one of them and make sure the text comes after.
</blockquote></details>

Still there.
___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 68 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViBFuOAtAwzzcmL9u8:-NW1nIfM2IdARpGJ629c:b-qnaxg9) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L68)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Missing icons + the button doesn't become enabled when I put it data
</blockquote></details>

Button still doesn't become enabled
___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 206 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViA_rrDQB_tCHk0LzL:-NW1nOGH6zwQ0vPoOrY0:b-f0c03c) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L206)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This is too small (probably needs to be a h4) and needs the brackets, and not 2 colons
</blockquote></details>

Still needs to brackets and not 2 colons

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29)* status: 6 of 21 files reviewed, 6 unresolved discussions (waiting on @faucomte97)

___
*[`frontend/src/pages/teacherDashboard/constants.ts` line 241 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NVRc-Go65ejAMXwEEKa:-NW7VKdm3kzFlNj3xuer:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/772e8b48d8c613d3500504d46cc7608819fad02b/frontend/src/pages/teacherDashboard/constants.ts#L241)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Will use auto-complete field with getNames() from 'country-list' that returns all the country names :)
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/TeacherAccount.tsx` line 144 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViCWzg0oZ6zykH_iVW:-NW7VLTX5M69MdGXUykt:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherAccount.tsx#L144)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Discussed :)
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/TeacherClasses.tsx` line 161 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViC4T32NMBY_mTL8F0:-NW7VMzY4vdfN-k1nJsx:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherClasses.tsx#L161)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 68 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViBFuOAtAwzzcmL9u8:-NW7VO0P2F8eziA0Bitc:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L68)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

This needs the autocomplete fix, hence it is parked
</blockquote></details>

Done.

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 2 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29)* status: all files reviewed, 3 unresolved discussions (waiting on @KamilPawel)

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`frontend/src/app/router.tsx` line 64 at r8](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NW7dJOu693bSaCW6-4c:-NW7oy91E-inxA0QHUq0:b-5q45gg) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/578655020ceebe2a8c3c896a15790a5933e6498c/frontend/src/app/router.tsx#L64)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

why is this here?
</blockquote></details>

merging main :c
___
*[`frontend/src/pages/teacherDashboard/TeacherAccount.tsx` line 62 at r8](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NW7f3y49NiSg9FfCVmP:-NW7osbj4LkQRvPK98cH:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/578655020ceebe2a8c3c896a15790a5933e6498c/frontend/src/pages/teacherDashboard/TeacherAccount.tsx#L62)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This button text is wrong :(
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 68 at r4](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NViBFuOAtAwzzcmL9u8:-NW7rGS6DDOhawoB8GFN:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/77dc932fe24133b56df8057ef92005aeb8ead3b6/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L68)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I see it works but only if you change the country - we need to have it enabled by default when the current country is already selected in the dropdown
</blockquote></details>

Done.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29)* status: all files reviewed, 3 unresolved discussions (waiting on @KamilPawel)

___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 159 at r12](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NW7ts9f7EYiSLqxI75r:-NW7ts9f7EYiSLqxI75s:b-ruy6tt) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d6bfd344466a735501c5bb11ed32cb375985d836/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L159)):*
> ```XML
> };
> 
> const TeachersTableActions: React.FC<{
> ```

You're missing 2 action buttons still, the "Resend invite" one and the "Disable 2FA" one
___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 176 at r12](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NW7tmp8BZjJuo8VaPnN:-NW7tmp8BZjJuo8VaPnO:bxenp5p) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d6bfd344466a735501c5bb11ed32cb375985d836/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L176)):*
> ```XML
>           Revoke admin
>         </Button>
>         <Button color="error">Delete</Button>
> ```

no icon here
___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 199 at r12](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NW7tzl78-A18x_mgfa0:-NW7tzl78-A18x_mgfa1:btsv9us) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d6bfd344466a735501c5bb11ed32cb375985d836/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L199)):*
> ```XML
>             <CflTableCellElement>
>               <Typography variant="subtitle1">
>                 {teacherName} {teacherEmail === email ? '(you)' : ''}{' '}
> ```

the "you" should be bold

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29)* status: 19 of 21 files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 159 at r12](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NW7ts9f7EYiSLqxI75r:-NW9x0N5BUblmNjTjSrH:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d6bfd344466a735501c5bb11ed32cb375985d836/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L159)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You're missing 2 action buttons still, the "Resend invite" one and the "Disable 2FA" one
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 176 at r12](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NW7tmp8BZjJuo8VaPnN:-NW8N8QF9E8V2RHglZ8x:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d6bfd344466a735501c5bb11ed32cb375985d836/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L176)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

no icon here
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/TeacherSchool.tsx` line 199 at r12](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NW7tzl78-A18x_mgfa0:-NW8NltM9ivVOz45Jk0n:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/d6bfd344466a735501c5bb11ed32cb375985d836/frontend/src/pages/teacherDashboard/TeacherSchool.tsx#L199)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

the "you" should be bold
</blockquote></details>

Done.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29)* status: all files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[`frontend/src/pages/teacherDashboard/dummyMethods.ts` line 40 at r13](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-NWCKcCH2Pw6tr16RuzF:-NWCKcCH2Pw6tr16RuzG:b-6wgh95) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e3c89d45d85aad531d79e3dfd77f95894793b034/frontend/src/pages/teacherDashboard/dummyMethods.ts#L40)):*
> ```XML
> }
> 
> export interface TeacherInvitesProps {
> ```

no logick

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/29#-:-NWCObBD3mI31tBXgtMZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Pull request merged**
