### PR TITLE
Fix otp

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305)* status: 0 of 7 files reviewed, 2 unresolved discussions

___
*[`backend/Pipfile` line 10 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305#-Nqn9Na317BITc-ahGyS:-Nqn9Na317BITc-ahGyT:b-780apq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/8ba63003913b46146f746834598f5861b047be8e/backend/Pipfile#L10)):*
> ```TOML
> #   https://github.com/ocadotechnology/codeforlife-package-python/blob/{ref}/Pipfile
> # Replace "{ref}" in the above URL with the ref set below.
> codeforlife = {ref = "fix_otp", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> ```

reminder: use new version
___
*[`backend/Pipfile` line 37 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305#-Nqn9R2R6u3KnxRImFQu:-Nqn9R2R6u3KnxRImFQv:b-780apq) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/8ba63003913b46146f746834598f5861b047be8e/backend/Pipfile#L37)):*
> ```TOML
> #   https://github.com/ocadotechnology/codeforlife-package-python/blob/{ref}/Pipfile
> # Replace "{ref}" in the above URL with the ref set below.
> codeforlife = {ref = "fix_otp", git = "https://github.com/ocadotechnology/codeforlife-package-python.git", extras = ["dev"]}
> ```

reminder: use new version

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/tests/serializers/test_auth_factor.py` line 32 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305#-NqnAkSBDH0zU9aBIEdl:-NqnAkSBDH0zU9aBIEdm:bbnsmkk) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/8ba63003913b46146f746834598f5861b047be8e/backend/api/tests/serializers/test_auth_factor.py#L32)):*
> ```Python
>         assert not self.uni_auth_factor_teacher_user.auth_factors.exists()
> 
>     # test: validate
> ```

Do we need these?
___
*[`backend/api/tests/serializers/test_auth_factor.py` line 35 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305#-NqnA_wx4loTnGTriHIg:-NqnA_wx4loTnGTriHIh:b-7yv2fe) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/8ba63003913b46146f746834598f5861b047be8e/backend/api/tests/serializers/test_auth_factor.py#L35)):*
> ```Python
> 
>     def test_validate_type__already_exists(self):
>         """Validate type is not doing this."""
> ```

What?
___
*[`backend/api/tests/views/test_auth_factor.py` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305#-NqnAhoO9I4YR_daxfop:-NqnAhoP5qBbh00OxJAp:bbnsmkk) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/8ba63003913b46146f746834598f5861b047be8e/backend/api/tests/views/test_auth_factor.py#L31)):*
> ```Python
>         assert not self.uni_auth_factor_teacher_user.auth_factors.exists()
> 
>     # test: get queryset
> ```

Do we need these?

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`backend/api/tests/serializers/test_auth_factor.py` line 32 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305#-NqnAkSBDH0zU9aBIEdl:-NqnBS01A47U-Rpd5Ulh:b-c19gz1) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/8ba63003913b46146f746834598f5861b047be8e/backend/api/tests/serializers/test_auth_factor.py#L32)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we need these?
</blockquote></details>

let's discuss in call.
___
*[`backend/api/tests/serializers/test_auth_factor.py` line 35 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305#-NqnA_wx4loTnGTriHIg:-NqnB-OhAGT29lHsJO5p:b-i1sw27) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/8ba63003913b46146f746834598f5861b047be8e/backend/api/tests/serializers/test_auth_factor.py#L35)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

What?
</blockquote></details>

looooooooooooooooooooooooooooooooool. Fixed.
___
*[`backend/api/tests/views/test_auth_factor.py` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305#-NqnAhoO9I4YR_daxfop:-NqnBV108tKHITpoVZ8t:b-c19gz1) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/8ba63003913b46146f746834598f5861b047be8e/backend/api/tests/views/test_auth_factor.py#L31)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we need these?
</blockquote></details>

let's discuss in call.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/305)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
