### PR TITLE
Create class

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/serializers/klass.py` line 16 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq28JpJEKX8AyJCdoIO:-Nq28JpKA9E7qMOhj6yM:b9akqg1) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/545d450e1c1beaa42739ec02a0e6e17021b5529e/backend/api/serializers/klass.py#L16)):*
> ```Python
> # pylint: disable-next=missing-class-docstring,too-many-ancestors
> class ClassSerializer(_ClassSerializer):
>     teacher = serializers.IntegerField(
> ```

Make teacher not required, grab request.user.teacher if teacher is non-admin
___
*[`backend/api/serializers/klass.py` line 20 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq28gBmDWYBpPZow_S7:-Nq28gBmDWYBpPZow_S8:b-vr46q8) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/545d450e1c1beaa42739ec02a0e6e17021b5529e/backend/api/serializers/klass.py#L20)):*
> ```Python
>     )
> 
>     school = serializers.IntegerField(
> ```

Remove this field and automatically assign the school to be the teacher's school
___
*[`backend/api/serializers/klass.py` line 62 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq25A_Y62w89FKejJdw:-Nq25A_Y62w89FKejJdx:b-14rabn) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/545d450e1c1beaa42739ec02a0e6e17021b5529e/backend/api/serializers/klass.py#L62)):*
> ```Python
>             access_code = get_random_string(
>                 length=5,
>                 allowed_chars=string.ascii_uppercase + string.digits,
> ```

Remove digits
___
*[`backend/api/tests/serializers/test_klass.py` line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq29CyU363rESZk7DOe:-Nq29CyU363rESZk7DOf:befvsav) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/545d450e1c1beaa42739ec02a0e6e17021b5529e/backend/api/tests/serializers/test_klass.py#L23)):*
> ```Python
>         self.class_1 = Class.objects.get(name="Class 1 @ School 1")
> 
>     def test_validate_name__name_not_unique(self):
> ```

Add test to check admin teacher can't create a class for teacher outside of school
___
*[`backend/api/tests/views/test_klass.py` line 83 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq293kx7dJXANixJd6y:-Nq293kx7dJXANixJd6z:b-ta13pm) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/545d450e1c1beaa42739ec02a0e6e17021b5529e/backend/api/tests/views/test_klass.py#L83)):*
> ```Python
>         )
> 
>     def test_create(self):
> ```

Add a test checking that admin teacher can successfully create a class for a different teacher

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @SKairinos)

___
*[`backend/Pipfile` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq29Pui18RHyUb2ww5C:-Nq29Pui18RHyUb2ww5D:b-ikoamk) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/545d450e1c1beaa42739ec02a0e6e17021b5529e/backend/Pipfile#L31)):*
> ```TOML
> google-cloud-container = "==2.3.0"
> # "django-anymail[amazon_ses]" = "==7.0.*"
> codeforlife = {ref = "create_class", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> ```

update package

**Review by SKairinos — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-:-Nq2B_-y2B_ajn3w3Evc:bnfp4nl)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @faucomte97)

___
*[`backend/Pipfile` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq29Pui18RHyUb2ww5C:-Nq2B_hw7l3J2saKhosD:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/545d450e1c1beaa42739ec02a0e6e17021b5529e/backend/Pipfile#L31)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

update package
</blockquote></details>

Done.
___
*[`backend/api/serializers/klass.py` line 16 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq28JpJEKX8AyJCdoIO:-Nq3Yf_F5SGp67jEBCf0:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/545d450e1c1beaa42739ec02a0e6e17021b5529e/backend/api/serializers/klass.py#L16)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Make teacher not required, grab request.user.teacher if teacher is non-admin
</blockquote></details>

Done.
___
*[`backend/api/serializers/klass.py` line 20 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq28gBmDWYBpPZow_S7:-Nq2DEvS1wTPnCTyybvk:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/545d450e1c1beaa42739ec02a0e6e17021b5529e/backend/api/serializers/klass.py#L20)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove this field and automatically assign the school to be the teacher's school
</blockquote></details>

Done.
___
*[`backend/api/serializers/klass.py` line 62 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq25A_Y62w89FKejJdw:-Nq2DD5oEJV3DILKuORG:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/545d450e1c1beaa42739ec02a0e6e17021b5529e/backend/api/serializers/klass.py#L62)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove digits
</blockquote></details>

Done.
___
*[`backend/api/tests/serializers/test_klass.py` line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq29CyU363rESZk7DOe:-Nq3aYqC1cdD39QCy7Na:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/545d450e1c1beaa42739ec02a0e6e17021b5529e/backend/api/tests/serializers/test_klass.py#L23)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Add test to check admin teacher can't create a class for teacher outside of school
</blockquote></details>

Done.
___
*[`backend/api/tests/views/test_klass.py` line 83 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq293kx7dJXANixJd6y:-Nq3cZws6ht2Yxjl6p4P:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/545d450e1c1beaa42739ec02a0e6e17021b5529e/backend/api/tests/views/test_klass.py#L83)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Add a test checking that admin teacher can successfully create a class for a different teacher
</blockquote></details>

Done.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262)* status: all files reviewed, 2 unresolved discussions (waiting on @SKairinos)

___
*[`backend/api/serializers/klass.py` line 46 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq7Einf3yPcgqLGXj66:-Nq7Eing07I4GSGEBBJa:b-8224y) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/37fe76ccbfa984c36699f22fa12164d077a57d0d/backend/api/serializers/klass.py#L46)):*
> ```Python
> 
>         user = self.request_school_teacher_user
>         if not queryset.filter(school=user.teacher.school_id).exists():
> ```

This seems to just check whether the request teacher's school exists (which it always will).
Instead, shouldn't this check whether `value != user.teacher.school_id`?
___
*[`backend/api/tests/views/test_klass.py` line 85 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-Nq7Gf8b3FqzKWAm5MYL:-Nq7Gf8b3FqzKWAm5MYM:b-gho1w3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/37fe76ccbfa984c36699f22fa12164d077a57d0d/backend/api/tests/views/test_klass.py#L85)):*
> ```Python
>     def test_create__self(self):
>         """
>         Teacher can create a class with their self as the class owner.
> ```

themself

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/262#-:-Nq7Q0J25j_VlEH4405p:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
