### PR TITLE
fix: add new logic

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/79)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/79)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/79#-N_sSdm5D6sYc79-C3Z6:-N_sSdm5D6sYc79-C3Z7:b-8zkq23) (no related file):*
Please update logic in frontend for CFL password fields

___

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/79)* status: 3 of 11 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/79#-N_sSdm5D6sYc79-C3Z6:-N_xu_bfAVOeT4tMRQ7t:b-896fix) (no related file):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Please update logic in frontend for CFL password fields
</blockquote></details>

Done.

___

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/79#-:-N_zaqm6-Wa2C6YjaprJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/79)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
