### PR TITLE
feat: teacher views dashboard

### PR DESCRIPTION
**Pull request by cewei8483**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173)

### CODE REVIEW

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173)* status: all files reviewed, 11 unresolved discussions (waiting on @cewei8483)

___
*[`backend/portal/views/teacher/dashboard.py` line 256 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-NdogL3lDJfBR7amrlQ_:-NdogL3lDJfBR7amrlQa:b-xd0x2o) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/backend/portal/views/teacher/dashboard.py#L256)):*
> ```Python
> 
>     form_data = request.POST
>     invite_teacher_form = InviteTeacherForm(request.POST)
> ```

Why not use the form_data in the InviteTeacherForm :thinking: 
___
*[`backend/portal/views/teacher/dashboard.py` line 294 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndokfqj98KGryXy3jqo:-Ndokfqj98KGryXy3jqp:b4w2a2v) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/backend/portal/views/teacher/dashboard.py#L294)):*
> ```Python
>     if teacher == user or (teacher.school != user.school or not user.is_admin):
>         return False
> ```

return True :joy: 
___
*[`backend/portal/views/teacher/dashboard.py` line 505 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp0mTPB1So7FhQcIiX:-Ndp0mTPB1So7FhQcIiY:b8iu5ty) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/backend/portal/views/teacher/dashboard.py#L505)):*
> ```Python
>     Check student is awaiting decision on request
>     """
>     if not student.pending_class_request:
> ```

I don't know if we should do the same here with only returning either a boolean or a HttpResponse? Feels a bit odd.. since we are just transferring the logic it could be fine I guess
___
*[`frontend/src/app/api/organisation.ts` line 33 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp2OiU6Hi6ilWwPsaB:-Ndp2OiU6Hi6ilWwPsaC:b-qu2gby) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/app/api/organisation.ts#L33)):*
> ```XML
>     }),
>     leaveOrganisation: build.mutation<{
>       source?: string;
> ```

Is this to check how was the invite sent?
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 122 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp2smn7zCqAoMfoX5B:-Ndp2smn7zCqAoMfoX5C:b-f6q1rg) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/YourSchool.tsx#L122)):*
> ```XML
> 
> const UpdateSchoolDetailsForm: React.FC<{
>   schoolData: any;
> ```

Can we please define the type :sweat_smile: 
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 314 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp3RJ13_Tmy7_tJCgQ:-Ndp3RJ13_Tmy7_tJCgR:b-12dvdb) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/YourSchool.tsx#L314)):*
> ```XML
> }> = ({ isUserAdmin, teachersData, sentInvites }) => {
>   // const { email } = getUser();
>   const email = 'alberteinstein@codeforlife.com';
> ```

Can this not be pulled from the API?
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 400 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp3Zzr9DzyMaTJU6DU:-Ndp3Zzr9DzyMaTJU6DV:bs6qvsh) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/YourSchool.tsx#L400)):*
> ```XML
> 
> const YourSchool: React.FC<{
>   data: any;
> ```

Here as well
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 413 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp4oSSBBD8G3v192as:-Ndp4oSSBBD8G3v192at:b14nsct) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/YourSchool.tsx#L413)):*
> ```XML
>         if (res?.classes) {
>           navigate(paths.teacher.dashboard.school.leave._, {
>             state: {
> ```

If we use Stefan's approach with { state: { index: <number>, props: { children: [ ..... we do't need to redifine the page.notification
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 427 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp5iDDBP1fDTzykZC7:-Ndp5iDDBP1fDTzykZC8:bsevvw7) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/YourSchool.tsx#L427)):*
> ```XML
> 
>   return <>
>     {location.state?.message &&
> ```

Then this can be removed
___
*[`frontend/src/pages/teacherDashboard/classes/Classes.tsx` line 237 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp6NiG4dSB-fVy0iJ_:-Ndp6NiG4dSB-fVy0iJa:bczmudl) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/classes/Classes.tsx#L237)):*
> ```XML
>   const findNewTeacherId = (name: string): number => {
>     const t = teacherList.find((t: teacherListType) => (t.fullName === name));
>     return t ? (t.id) : -1;
> ```

A bit more descriptive name please :joy: 
___
*[`frontend/src/pages/teacherDashboard/classes/Classes.tsx` line 322 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp6btB6WoNI4mf_LLN:-Ndp6btB6WoNI4mf_LLO:b-x8tegk) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/classes/Classes.tsx#L322)):*
> ```XML
>     <>
>       <Page.Notification>
>         {location.state.source === 'organisationKick'
> ```

Can we not reuse the Stefan Notification as well?

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173)* status: 6 of 12 files reviewed, 11 unresolved discussions (waiting on @KamilPawel)

___
*[`backend/portal/views/teacher/dashboard.py` line 256 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-NdogL3lDJfBR7amrlQ_:-NdpeF5dAD8jrJgDtv1c:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/backend/portal/views/teacher/dashboard.py#L256)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Why not use the form_data in the InviteTeacherForm :thinking:
</blockquote></details>

Done.
___
*[`backend/portal/views/teacher/dashboard.py` line 294 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndokfqj98KGryXy3jqo:-NdpeHkJA3VoXg_ADWSK:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/backend/portal/views/teacher/dashboard.py#L294)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

return True :joy:
</blockquote></details>

Done.
___
*[`backend/portal/views/teacher/dashboard.py` line 505 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp0mTPB1So7FhQcIiX:-NdpbnRy7IpJ0Cv64v_f:bbu41zl) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/backend/portal/views/teacher/dashboard.py#L505)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

I don't know if we should do the same here with only returning either a boolean or a HttpResponse? Feels a bit odd.. since we are just transferring the logic it could be fine I guess
</blockquote></details>

This function is not used in this task, so I left it as it is.
___
*[`frontend/src/app/api/organisation.ts` line 33 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp2OiU6Hi6ilWwPsaB:-NdpbJL17jGJ8So1NhZf:b5tfv0f) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/app/api/organisation.ts#L33)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Is this to check how was the invite sent?
</blockquote></details>

The endpoint will be called by two functions, `organisationKick` and `leaveOrganisation`. This variable is to distinguish them.
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 122 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp2smn7zCqAoMfoX5B:-Ne3HDAO88wi3zX5bW_P:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/YourSchool.tsx#L122)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Can we please define the type :sweat_smile:
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 314 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp3RJ13_Tmy7_tJCgQ:-Ne3HHT81bpGYtfczeFh:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/YourSchool.tsx#L314)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Can this not be pulled from the API?
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 400 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp3Zzr9DzyMaTJU6DU:-Ne3HIM27D0jttT5gnoL:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/YourSchool.tsx#L400)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Here as well
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 413 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp4oSSBBD8G3v192as:-NdpaeeL0uF32EpWC4qP:b-ti6t4c) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/YourSchool.tsx#L413)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

If we use Stefan's approach with { state: { index: <number>, props: { children: [ ..... we do't need to redifine the page.notification
</blockquote></details>

As you said, the notification will then appear above the page banner
___
*[`frontend/src/pages/teacherDashboard/YourSchool.tsx` line 427 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp5iDDBP1fDTzykZC7:-Ndpc5w3BMdavDi8UFVl:biq8zda) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/YourSchool.tsx#L427)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Then this can be removed
</blockquote></details>

Explained above
___
*[`frontend/src/pages/teacherDashboard/classes/Classes.tsx` line 237 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp6NiG4dSB-fVy0iJ_:-NdpeMc64PDKXzVx6jTI:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/classes/Classes.tsx#L237)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

A bit more descriptive name please :joy:
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/classes/Classes.tsx` line 322 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-Ndp6btB6WoNI4mf_LLN:-Ndpaqkq3yfpT5FiZfM3:b-35ha2y) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/74da4130f57a0d788696f094647886965b37ba88/frontend/src/pages/teacherDashboard/classes/Classes.tsx#L322)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Can we not reuse the Stefan Notification as well?
</blockquote></details>

Same reason above

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r3, 4 of 4 files at r4, 6 of 6 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173)* status: all files reviewed, 1 unresolved discussion (waiting on @cewei8483)

___
*[`frontend/src/app/api/teacher/dashboard.ts` line 76 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-NeNMuvs6KO5sbKXkhcO:-NeNMuvs6KO5sbKXkhcP:b-s88giw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/dd2293d6dea17de507208428a520dbcd0eb372fc/frontend/src/app/api/teacher/dashboard.ts#L76)):*
> ```XML
>       providesTags: ['teacher']
>     }),
>     inviteTeacher: build.mutation<any, {
> ```

if the function doesn't need the attribute replace any with null, else define the type

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173)* status: 9 of 12 files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[`frontend/src/app/api/teacher/dashboard.ts` line 76 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173#-NeNMuvs6KO5sbKXkhcO:-NeNTJaI4WFMmDLzt23o:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/dd2293d6dea17de507208428a520dbcd0eb372fc/frontend/src/app/api/teacher/dashboard.ts#L76)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

if the function doesn't need the attribute replace any with null, else define the type
</blockquote></details>

Done.

**Review by KamilPawel — APPROVED** [review]
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/173)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Pull request merged**
