### PR TITLE
Fix router

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/61)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/61)* status: 0 of 78 files reviewed, 1 unresolved discussion

___
*[`frontend/src/features/header/Header.tsx` line 34 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/61#-NZRUXDA55KqXfQrP8A_:-NZRUXDB8ZiC6caEb8K7:bdl388y) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/01b76380faec2bce4102ee35ac9b7e85863ffb16/frontend/src/features/header/Header.tsx#L34)):*
> ```XML
>   React.useEffect(() => {
>     console.log('Header mounted!!!');
>   }, []);
> ```

todo: remove console.log

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 78 of 78 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/61)* status: all files reviewed, 4 unresolved discussions (waiting on @SKairinos)

___
*[`frontend/src/pages/emailVerification/EmailVerification.tsx` line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/61#-NZRYbjU-CAYzUBdV22q:-NZRYbjU-CAYzUBdV22r:b-5jb330) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/01b76380faec2bce4102ee35ac9b7e85863ffb16/frontend/src/pages/emailVerification/EmailVerification.tsx#L23)):*
> ```XML
>         .oneOf([
>           'teacher',
>           'student',
> ```

Students don't have an email so can't verify their email
___
*[`frontend/src/pages/newsletter/Newsletter.tsx` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/61#-NZRZLsQChwWB0othwZS:-NZRZLsREuiaKxSY6mdn:b-rab8hw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2e2a75f463e89a28bfce817ee84389a739f0d637/frontend/src/pages/newsletter/Newsletter.tsx#L1)):*
> ```XML
> import React from 'react';
> ```

Why was this file deleted?
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 268 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/61#-NZRa-Qe9RYDJkJ2TIK-:-NZRa-Qe9RYDJkJ2TIK0:b-5elmkz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/01b76380faec2bce4102ee35ac9b7e85863ffb16/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L268)):*
> ```XML
>     )?.studentIds;
> 
>     console.log(studentIds);
> ```

remove log

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/61)* status: 74 of 78 files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`frontend/src/pages/emailVerification/EmailVerification.tsx` line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/61#-NZRYbjU-CAYzUBdV22q:-NZVCdpX8GaqV_uAe9OM:blix6fx) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/01b76380faec2bce4102ee35ac9b7e85863ffb16/frontend/src/pages/emailVerification/EmailVerification.tsx#L23)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Students don't have an email so can't verify their email
</blockquote></details>

good catch. I removed it.
___
*[`frontend/src/pages/newsletter/Newsletter.tsx` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/61#-NZRZLsQChwWB0othwZS:-NZVDy3Z5LEetpp9q0q8:bi4zy3z) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2e2a75f463e89a28bfce817ee84389a739f0d637/frontend/src/pages/newsletter/Newsletter.tsx#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Why was this file deleted?
</blockquote></details>

Ahh, yes! Forgot to tell yo this. It was a duplicate page of the /communication-preferences page.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 268 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/61#-NZRa-Qe9RYDJkJ2TIK-:-NZVEPGPCfIHn4GyNQzm:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/01b76380faec2bce4102ee35ac9b7e85863ffb16/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L268)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

remove log
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
