### PR TITLE
fix: 2045 home page

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/6)

### CODE REVIEW

**Review by cewei8483 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/6)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`src/pages/home/Home.tsx` line 24 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/6#-NSzQqxU644vr3aR25oa:-NSzQqxU644vr3aR25ob:bmixkxm) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/327e258a09098827d810a9446a233f3c0d97a71b/src/pages/home/Home.tsx#L24)):*
> ```XML
>         ${theme.palette.secondary.main} 0
>       )`}>
>         <TargetAudience />
> ```

Maybe because it is wrapped by PageSection component now, the content seems to be pushed to the middle:

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/6)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @cewei8483)

___
*[`src/pages/home/Home.tsx` line 24 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/6#-NSzQqxU644vr3aR25oa:-NSzWjoH56O62rFWaFKm:bi4l8gt) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/327e258a09098827d810a9446a233f3c0d97a71b/src/pages/home/Home.tsx#L24)):*
>  is wrapped by PageSection component now, the content seems to be pushed to the middle:
This is the intended behavior. It was a mistake on the original site (I checked with Laura). All pages should be a collection of PageSections so they have a maxWidth.

**Review by cewei8483 — APPROVED** [review]
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by SKairinos — COMMENTED** [review]
> Reviewed 14 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
