### PR TITLE
Update teacher

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/263)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/263)* status: 0 of 10 files reviewed, 1 unresolved discussion

___
*[`backend/Pipfile` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/263#-NqCRegL3_shcf6oBPGb:-NqCRegM23Zg0rhOQhPm:blxalqy) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f664de16b978f2a3a79e2dd9d172cb793df16e88/backend/Pipfile#L31)):*
> ```TOML
> google-cloud-container = "==2.3.0"
> # "django-anymail[amazon_ses]" = "==7.0.*"
> codeforlife = {ref = "update_teacher", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> ```

use new version

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/263)* status: 0 of 10 files reviewed, 2 unresolved discussions

___
*[`backend/api/tests/serializers/test_teacher.py` line 26 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/263#-NqCUpue53y50zEcQm6K:-NqCUpue53y50zEcQm6L:b2b775) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f664de16b978f2a3a79e2dd9d172cb793df16e88/backend/api/tests/serializers/test_teacher.py#L26)):*
> ```Python
>             email="admin.teacher@school1.com",
>         )
>         assert self.admin_school_teacher_user
> ```

remove this assert

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/263)* status: 0 of 10 files reviewed, 3 unresolved discussions

___
*[`backend/api/tests/serializers/test_teacher.py` line 63 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/263#-NqCVcvK5Ykq2Olaa037:-NqCVcvL9QjYdSHRIeUv:byuop87) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f664de16b978f2a3a79e2dd9d172cb793df16e88/backend/api/tests/serializers/test_teacher.py#L63)):*
> ```Python
>     def test_validate__not_in_school(self):
>         """
>         Teacher cannot update own permissions.
> ```

update docstring

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/263)* status: 0 of 10 files reviewed, 4 unresolved discussions

___
*[`backend/api/serializers/teacher.py` line 43 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/263#-NqCY1Tv0yOqebvvggHx:-NqCY1Tv0yOqebvvggHy:b-m79c0t) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f664de16b978f2a3a79e2dd9d172cb793df16e88/backend/api/serializers/teacher.py#L43)):*
> ```Python
>                 )
> 
>             user = self.request_school_teacher_user
> ```

unnecessary as the queryset should limit you to only teachers in your school.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 10 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/263#-:-NqCnG7o9OMh1Sgsqovx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
