### PR TITLE
feat: teacher teach delete student

### PR DESCRIPTION
**Pull request by cewei8483**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/186)

### CODE REVIEW

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/186)* status: all files reviewed, 2 unresolved discussions (waiting on @cewei8483)

___
*[`backend/portal/views/teacher/teach.py` line 263 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/186#-NfzFjAbETyV6NY-Ohi_:-NfzFjAbETyV6NY-Ohia:bkaohmo) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/1a05f28d6f0ccd91e99484058443d89aad29a5ed/backend/portal/views/teacher/teach.py#L263)):*
> ```Python
>     return HttpResponseRedirect(reverse_lazy("dashboard") + "#classes")
> ```

Could you please add @required_POST here 
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 345 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/186#-NfzJQEEByPF5wnRfI65:-NfzJQEEByPF5wnRfI66:bnbsrex) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/1a05f28d6f0ccd91e99484058443d89aad29a5ed/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L345)):*
> ```XML
>           them permanently.
>         </Typography>
>         {studentData && <StudentsTable accessCode={accessCode} studentData={studentData} />}
> ```

Just curiosity, can we not do a null check as in way above to if (studentData === null) return, and then use the component normally?

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/186)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @KamilPawel)

___
*[`backend/portal/views/teacher/teach.py` line 263 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/186#-NfzFjAbETyV6NY-Ohi_:-NfzT9chDPyJT8dIRkqg:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/1a05f28d6f0ccd91e99484058443d89aad29a5ed/backend/portal/views/teacher/teach.py#L263)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Could you please add @required_POST here
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx` line 345 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/186#-NfzJQEEByPF5wnRfI65:-NfzTAMH9P7HeTIbttNF:b-e4dx7i) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/1a05f28d6f0ccd91e99484058443d89aad29a5ed/frontend/src/pages/teacherDashboard/classes/editClass/EditClass.tsx#L345)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Just curiosity, can we not do a null check as in way above to if (studentData === null) return, and then use the component normally?
</blockquote></details>

To be discussed

**Review by KamilPawel — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Review by KamilPawel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Review by KamilPawel — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/186#-:-Nfzbzom-lDk1hgryETe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Review by SKairinos — APPROVED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Review by SKairinos — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Pull request merged**
