### PR TITLE
feat: update details, delete account, disable 2fa

### PR DESCRIPTION
**Pull request by KamilPawel**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179)

### CODE REVIEW

**Review by cewei8483 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179)* status: 0 of 11 files reviewed, 6 unresolved discussions (waiting on @KamilPawel)

___
*[`backend/portal/helpers/password.py` line 144 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-Nex8xko53ugJdmIA8XK:-Nex8xko53ugJdmIA8XL:bcbmk8w) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0d75ef7728b86185f2289203dbbe787679ae2a9a/backend/portal/helpers/password.py#L144)):*
> ```Python
>     if data.get("new_password", "") != "":
>         changing_password = True
>         user.set_password(data["new_password"])
> ```

Do we need to check password strength here? Asking this because I can set a super-simple new password.
___
*[`backend/portal/views/teacher/dashboard.py` line 242 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-Nex9w1D8jJUiOtVM7fK:-Nex9w1D8jJUiOtVM7fL:b-6wxbrs) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0d75ef7728b86185f2289203dbbe787679ae2a9a/backend/portal/views/teacher/dashboard.py#L242)):*
> ```Python
>         try:
>             backup_tokens = request.user.staticdevice_set.all()[
>                 0
> ```

Don't think this is necessary :joy: 
___
*[`backend/portal/views/teacher/dashboard.py` line 250 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-NexA-tp1JeHr3pRKokf:-NexA-tp1JeHr3pRKokg:b-t2j6tr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0d75ef7728b86185f2289203dbbe787679ae2a9a/backend/portal/views/teacher/dashboard.py#L250)):*
> ```Python
> 
> 
> from django_otp.plugins.otp_totp.models import TOTPDevice
> ```

Move imports to the top of the file
___
*[`backend/portal/views/teacher/dashboard.py` line 301 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-NexAYQG6XGj67XqMqrI:-NexAYQG6XGj67XqMqrJ:br5tt48) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0d75ef7728b86185f2289203dbbe787679ae2a9a/backend/portal/views/teacher/dashboard.py#L301)):*
> ```Python
> 
>     return JsonResponse(
>         {"message": "Something went wrong"}, status=status.HTTP_400_BAD_REQUEST
> ```

Returning form.error here is more specific
___
*[`frontend/src/pages/teacherDashboard/account/YourAccount.tsx` line 166 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-NexOaPeBlTrk0wG_3Fo:-NexOaPeBlTrk0wG_3Fp:bhnxkle) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0d75ef7728b86185f2289203dbbe787679ae2a9a/frontend/src/pages/teacherDashboard/account/YourAccount.tsx#L166)):*
> ```XML
>           });
>         }
>         updateTeacherAccount(values).unwrap().then(() => {
> ```

I couldn't change the email :sweat_smile: 
___
*[`frontend/src/pages/teacherDashboard/account/YourAccount.tsx` line 261 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-NexMU7p53pLCgrf2rdc:-NexMU7p53pLCgrf2rdd:b-p27qhj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0d75ef7728b86185f2289203dbbe787679ae2a9a/frontend/src/pages/teacherDashboard/account/YourAccount.tsx#L261)):*
> ```XML
>         </Grid>
>         <Grid item xs={12} sm={4}>
>           <PasswordField
> ```

Is this password field always required?

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @cewei8483)

___
*[`backend/portal/helpers/password.py` line 144 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-Nex8xko53ugJdmIA8XK:-NfBienx86WB_W6ssYET:brmx1iw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0d75ef7728b86185f2289203dbbe787679ae2a9a/backend/portal/helpers/password.py#L144)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Do we need to check password strength here? Asking this because I can set a super-simple new password.
</blockquote></details>

This just checks if the password was changed, the password strength I think could be updated in another task :thinking: 
___
*[`backend/portal/views/teacher/dashboard.py` line 242 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-Nex9w1D8jJUiOtVM7fK:-NfBjIRv6YPvgOhOt7Am:b-uj4y5p) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0d75ef7728b86185f2289203dbbe787679ae2a9a/backend/portal/views/teacher/dashboard.py#L242)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Don't think this is necessary :joy:
</blockquote></details>

This may be needed later for implementing the 2fa endpoints?
___
*[`backend/portal/views/teacher/dashboard.py` line 250 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-NexA-tp1JeHr3pRKokf:-NfBjS4c9O_m_k6r4geb:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0d75ef7728b86185f2289203dbbe787679ae2a9a/backend/portal/views/teacher/dashboard.py#L250)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Move imports to the top of the file
</blockquote></details>

Done.
___
*[`backend/portal/views/teacher/dashboard.py` line 301 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-NexAYQG6XGj67XqMqrI:-NfBjsb44Q9iWE7xXrpu:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0d75ef7728b86185f2289203dbbe787679ae2a9a/backend/portal/views/teacher/dashboard.py#L301)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Returning form.error here is more specific
</blockquote></details>

Done.
___
*[`frontend/src/pages/teacherDashboard/account/YourAccount.tsx` line 166 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-NexOaPeBlTrk0wG_3Fo:-NfBjugH0Js2H_CnEjHp:b-f17d2o) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0d75ef7728b86185f2289203dbbe787679ae2a9a/frontend/src/pages/teacherDashboard/account/YourAccount.tsx#L166)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

I couldn't change the email :sweat_smile:
</blockquote></details>

Did you check what errors are returned, the form must be valid and usually requires password and email.. also I added a TODO when the getUser input is done, add pre-filled textfields for name and surname
___
*[`frontend/src/pages/teacherDashboard/account/YourAccount.tsx` line 261 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-NexMU7p53pLCgrf2rdc:-NfBju7U2DlRLY_CwCP5:b2nhswy) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/0d75ef7728b86185f2289203dbbe787679ae2a9a/frontend/src/pages/teacherDashboard/account/YourAccount.tsx#L261)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

Is this password field always required?
</blockquote></details>

Yes

**Review by cewei8483 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-:-NfC92TC6nPUupBtrfQI:bnfp4nl)* status: 0 of 11 files reviewed, all discussions resolved

**Review by cewei8483 — APPROVED** [review]
> Reviewed 8 of 11 files at r1, 1 of 2 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Review by KamilPawel — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-:-NfQ1CUS3iL70AHEooBc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Review by KamilPawel — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-:-NfQ1EXd9-6mPOz5fBF9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Review by cewei8483 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[`backend/portal/views/teacher/dashboard.py` line 399 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-Nfu1iWXAIcFYzr0Rh3Q:-Nfu1iWY8a0UURTWa5-4:b-appwpn) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/1024c8e5b4ce4b641ba7e755556c4a966b0fe36e/backend/portal/views/teacher/dashboard.py#L399)):*
> ```Python
>         )
>     else:
>         anchor = old_anchor
> ```

These are the old ones :joy: 
Should use your source:
```
return JsonResponse(
        {"message": "Your account details have been successfully changed."}
)

```

**Review by KamilPawel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @cewei8483)

___
*[`backend/portal/views/teacher/dashboard.py` line 399 at r6](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179#-Nfu1iWXAIcFYzr0Rh3Q:-Nfu7K4uDDA5hXvzdG2T:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/1024c8e5b4ce4b641ba7e755556c4a966b0fe36e/backend/portal/views/teacher/dashboard.py#L399)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

These are the old ones :joy: 
Should use your source:
```
return JsonResponse(
        {"message": "Your account details have been successfully changed."}
)

```
</blockquote></details>

Done.

**Review by cewei8483 — APPROVED** [review]
> Reviewed 4 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @KamilPawel)

**Pull request merged**
