### PR TITLE
Clean dependencies

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329)

### CODE REVIEW

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329)* status: all files reviewed, 7 unresolved discussions (waiting on @faucomte97)

___
*[`backend/Pipfile` line 28 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZgdJr-YUYpzgwOfuN:-NyZgdJr-YUYpzgwOfuO:bukmyg0) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L28)):*
> ```TOML
> codeforlife = {ref = "v0.16.8", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> # 🚫 Don't add [packages] below that are inhertited from the CFL package.
> django-csp = "==3.7"
> ```

do we need this? and should this not be in cfl package?
___
*[`backend/Pipfile` line 29 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZgWyRDwAckSQ1jGQp:-NyZgWyRDwAckSQ1jGQq:bukmyg0) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L29)):*
> ```TOML
> # 🚫 Don't add [packages] below that are inhertited from the CFL package.
> django-csp = "==3.7"
> django-import-export = "*"
> ```

do we need this? and should this not be in cfl package?
___
*[`backend/Pipfile` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZgefQ6WFWjFtwlA55:-NyZgefQ6WFWjFtwlA56:b-c3mkiz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L30)):*
> ```TOML
> django-csp = "==3.7"
> django-import-export = "*"
> django-recaptcha = "==2.0.6"
> ```

why are we keeping this?
___
*[`backend/Pipfile` line 42 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZgnIG8XcaUtj4ReJ5:-NyZgnIG8XcaUtj4ReJ6:b-c3mkiz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L42)):*
> ```TOML
> # codeforlife = {file = "../../codeforlife-package-python", editable = true, extras = ["dev"]}
> # 🚫 Don't add [dev-packages] below that are inhertited from the CFL package.
> django-test-migrations = "==1.2.0"
> ```

why are we keeping this?
___
*[`backend/Pipfile` line 43 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZtFpJ8FyfUZCh0eg6:-NyZtFpJ8FyfUZCh0eg7:b-wt2t8a) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L43)):*
> ```TOML
> # 🚫 Don't add [dev-packages] below that are inhertited from the CFL package.
> django-test-migrations = "==1.2.0"
> pytest-cov = "*"
> ```

this is already in py package dev deps
___
*[`backend/Pipfile` line 44 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZtMd91fV6XsTFzNfl:-NyZtMd91fV6XsTFzNfm:b-c3mkiz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L44)):*
> ```TOML
> django-test-migrations = "==1.2.0"
> pytest-cov = "*"
> pytest-mock = "*"
> ```

why are we keeping this?
___
*[`backend/Pipfile` line 45 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZtM9t4HlZr1b_Qrde:-NyZtM9t4HlZr1b_Qrdf:b-c3mkiz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L45)):*
> ```TOML
> pytest-cov = "*"
> pytest-mock = "*"
> pytest-order = "*"
> ```

why are we keeping this?

**Comment by SKairinos** [comment]
@faucomte97 , I reviewed this

**Review by faucomte97 — COMMENTED** [review]
@SKairinos replied

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-:-Ny_iAt77PBOPNCXfTkq:bc9auxl)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @SKairinos)

___
*[`backend/Pipfile` line 28 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZgdJr-YUYpzgwOfuN:-Ny_hUU15ixwAbGirT5U:bv5h37f) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L28)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

do we need this? and should this not be in cfl package?
</blockquote></details>

We'll need it for the CSP header - moving it to python package
___
*[`backend/Pipfile` line 29 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZgWyRDwAckSQ1jGQp:-Ny_hZe97QlAB5MPrkRG:b-n0d2yw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L29)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

do we need this? and should this not be in cfl package?
</blockquote></details>

We need to be able to quickly export user data from the Django admin in case users request to receive the data we hold on them - moving it to python package
___
*[`backend/Pipfile` line 30 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZgefQ6WFWjFtwlA55:-Ny_gPPDBucHSFdMV-RQ:ba3dfob) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L30)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why are we keeping this?
</blockquote></details>

Removed
___
*[`backend/Pipfile` line 42 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZgnIG8XcaUtj4ReJ5:-Ny_hpj24fiuqx1i_NpB:b-hiou7z) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L42)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why are we keeping this?
</blockquote></details>

Since we agreed we want to test custom migrations I assumed we'd want to keep this since this is what we use to do it. Moving it to cfl package
___
*[`backend/Pipfile` line 43 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZtFpJ8FyfUZCh0eg6:-Ny_g47j9uGotmQtTFrT:b-hfpv0l) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L43)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

this is already in py package dev deps
</blockquote></details>

removed
___
*[`backend/Pipfile` line 44 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZtMd91fV6XsTFzNfl:-Ny_hyuTDyU4sWU4trNE:ba3dfob) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L44)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why are we keeping this?
</blockquote></details>

Removed
___
*[`backend/Pipfile` line 45 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyZtM9t4HlZr1b_Qrde:-Ny_hyB0BnJ9w_XMBozQ:ba3dfob) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L45)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

why are we keeping this?
</blockquote></details>

Removed

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`backend/Pipfile` line 29 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyddxSi2oM_UcMa6Bd0:-NyddxSi2oM_UcMa6Bd1:b-3e7u5l) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2b2b9521f69b70f94f9007ac9ae2fa15e78a8746/backend/Pipfile#L29)):*
> ```TOML
> # 🚫 Don't add [packages] below that are inherited from the CFL package.
> pyjwt = "==2.6.0" # TODO: upgrade to latest version
> requests = "==2.31.0"
> ```

this should also be moved to the python package. it's needed in codeforlife/mail.py.

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`backend/Pipfile` line 29 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyddxSi2oM_UcMa6Bd0:-NyeNWTg8Vh5_2x65CGO:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2b2b9521f69b70f94f9007ac9ae2fa15e78a8746/backend/Pipfile#L29)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

this should also be moved to the python package. it's needed in codeforlife/mail.py.
</blockquote></details>

Done.

**Review by faucomte97 — COMMENTED** [review]
@SKairinos readdressed

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-:-NyeN_rUBMYX_ZB4_cPP:b-qtxa1s)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @SKairinos)

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`backend/Pipfile` line 29 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyddxSi2oM_UcMa6Bd0:-Nz3-ItaElsdo073m-K2:b7gm5tz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2b2b9521f69b70f94f9007ac9ae2fa15e78a8746/backend/Pipfile#L29)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you didn't add this in the python package

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`backend/Pipfile` line 29 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NyddxSi2oM_UcMa6Bd0:-Nz3-O5h9h1JQDNTn55w:bca951x) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/2b2b9521f69b70f94f9007ac9ae2fa15e78a8746/backend/Pipfile#L29)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

you didn't add this in the python package
</blockquote></details>

Also, don't you need to regenerate the Pipfile.lock? Please check and confirm

**Review by SKairinos — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`backend/Pipfile` line 26 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NzEBLB58MQA0aQfE_1Q:-NzEBLB58MQA0aQfE_1R:b1t4eis) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L26)):*
> ```TOML
> 
> [packages]
> codeforlife = {ref = "v0.16.8", git = "https://github.com/ocadotechnology/codeforlife-package-python.git"}
> ```

after you release the nee python package, please install it here

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`backend/Pipfile` line 26 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329#-NzEBLB58MQA0aQfE_1Q:-NzENAxPE58Vhl1KGNrE:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/10c724884c6a02757023d940ccffccdf8c92d7f2/backend/Pipfile#L26)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

after you release the nee python package, please install it here
</blockquote></details>

Done.

**Review by SKairinos — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/329)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Pull request merged**
