### PR TITLE
fix: New portal edits - teacher/2FA

### PR DESCRIPTION
**Pull request by cewei8483**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/139)

### CODE REVIEW

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/139)* status: all files reviewed, 1 unresolved discussion (waiting on @cewei8483)

___
*[`frontend/src/pages/teacherDashboard/account/2fa/setup2fa/Setup2fa.tsx` line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/139#-NbsO46l6WvePW7pjqzI:-NbsO46l6WvePW7pjqzJ:bf7xx35) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/9043b6509bdc460ad8d9566cf8c311f6feb8d811/frontend/src/pages/teacherDashboard/account/2fa/setup2fa/Setup2fa.tsx#L67)):*
> ```XML
>             onSubmit={(values, { setSubmitting }) => {
>               // TODO: to call backend
>               setSubmitting(false);
> ```

Can we also remove setSubmitting :sweat_smile:

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/139)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[`frontend/src/pages/teacherDashboard/account/2fa/setup2fa/Setup2fa.tsx` line 67 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/139#-NbsO46l6WvePW7pjqzI:-NbspwSm29KfralsP40t:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/9043b6509bdc460ad8d9566cf8c311f6feb8d811/frontend/src/pages/teacherDashboard/account/2fa/setup2fa/Setup2fa.tsx#L67)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Can we also remove setSubmitting :sweat_smile:
</blockquote></details>

Done.

**Review by KamilPawel — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/139)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @cewei8483)

**Review by KamilPawel — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/139)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Pull request merged**
