### PR TITLE
use sso service

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178)* status: 0 of 37 files reviewed, 2 unresolved discussions

___
*[`frontend/package.json` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178#-NenLqAG3lmcXjZG9WvB:-NenLqAG3lmcXjZG9WvC:b-tsnf28) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f7b88063b32e30709942e05ad8091f5f8d0041ca/frontend/package.json#L31)):*
> ```JSON
>     "@mui/material": "^5.11.12",
>     "@reduxjs/toolkit": "^1.9.3",
>     "codeforlife": "github:ocadotechnology/codeforlife-package-javascript#sso",
> ```

todo: install specific version
___
*[`frontend/src/app/api/api.ts` line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178#-NenMBOlAzaW7CuAkpif:-NenMBOlAzaW7CuAkpig:bvslql3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f7b88063b32e30709942e05ad8091f5f8d0041ca/frontend/src/app/api/api.ts#L23)):*
> ```XML
> // TODO: remove this hot switching code and migrate login pages to SSO service.
> const ssoFetch = fetchBaseQuery({
>   baseUrl: `http://localhost:8001/${SSO_SERVICE_NAME}/api/`,
> ```

support online base url

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 26 of 37 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`backend/service/urls.py` line 20 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178#-NfFu_nJ0Uxp_StSzWb9:-NfFu_nJ0Uxp_StSzWbA:b9425i9) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/9d399d4cda28ea4b8025ddb44593fdcf5509c717/backend/service/urls.py#L20)):*
> ```Python
> 
> urlpatterns = service_urlpatterns(
>     api_urls_path="portal.urls",  # TODO: standardize path
> ```

Does using this instead mean that we no longer have the admin urls? Or are they included?
___
*[`frontend/package.json` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178#-NenLqAG3lmcXjZG9WvB:-NfFuYkv4OpwxI3yFNPH:b-l0cuig) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f7b88063b32e30709942e05ad8091f5f8d0041ca/frontend/package.json#L31)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

todo: install specific version
</blockquote></details>

This is done right?
___
*[`frontend/src/app/api/api.ts` line 23 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178#-NenMBOlAzaW7CuAkpif:-NfFuWdx0P-lhTLs0XjD:bsoodxz) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f7b88063b32e30709942e05ad8091f5f8d0041ca/frontend/src/app/api/api.ts#L23)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

support online base url
</blockquote></details>

Reminder

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`backend/service/urls.py` line 20 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178#-NfFu_nJ0Uxp_StSzWb9:-NfG5J8Q9jNxxokD99ul:b-kq58f4) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/9d399d4cda28ea4b8025ddb44593fdcf5509c717/backend/service/urls.py#L20)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Does using this instead mean that we no longer have the admin urls? Or are they included?
</blockquote></details>

[they're included](https://github.com/ocadotechnology/codeforlife-package-python/blob/d8a3f6963507996d862011604786b2e0c3d63d70/codeforlife/urls.py#L18C14-L18C19)
___
*[`frontend/package.json` line 31 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178#-NenLqAG3lmcXjZG9WvB:-NfG5hPd9EGgiYDwWbX6:bx5l4q) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/f7b88063b32e30709942e05ad8091f5f8d0041ca/frontend/package.json#L31)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

This is done right?
</blockquote></details>

yes. we're using v1.27.4

**Review by faucomte97 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/178#-:-NfG9X7PCRdA1VR0HsaS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
