### PR TITLE
feat: 16 organisation views

### PR DESCRIPTION
**Pull request by cewei8483**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147)

### CODE REVIEW

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147)* status: all files reviewed, 5 unresolved discussions (waiting on @cewei8483)

___
*[`frontend/src/app/api/endpoints/organisation.ts` line 27 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147#-NcYs8IC4UVmmbgLUhKf:-NcYs8IC4UVmmbgLUhKg:bh01ezr) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6b638e8aa45af063a73c2c8b5ccc0f12e0057f6b/frontend/src/app/api/endpoints/organisation.ts#L27)):*
> ```XML
>         body,
>         headers: {
>           'Content-Type': 'application/x-www-form-urlencoded'
> ```

Didn't we already add this to the default header?
___
*[`frontend/src/app/api/endpoints/organisation.ts` line 42 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147#-NcYsB_k72QZuEsrDq-m:-NcYsB_k72QZuEsrDq-n:brhun0a) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6b638e8aa45af063a73c2c8b5ccc0f12e0057f6b/frontend/src/app/api/endpoints/organisation.ts#L42)):*
> ```XML
>         body,
>         headers: {
>           'Content-Type': 'application/x-www-form-urlencoded'
> ```

Same here?
___
*[`frontend/src/components/form/SchoolCountryField.tsx` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147#-NcYsO2WDqOFUGQv5WP0:-NcYsO2WDqOFUGQv5WP1:b-7davyn) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6b638e8aa45af063a73c2c8b5ccc0f12e0057f6b/frontend/src/components/form/SchoolCountryField.tsx#L12)):*
> ```XML
>     code: 'TW',
>     name: 'Taiwan'
>   }]);
> ```

Is this to prefill with dummy data?
___
*[`frontend/src/components/form/SchoolNameField.tsx` line 17 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147#-NcYtYZE7peVReIVjt65:-NcYtYZE7peVReIVjt66:b3n9zmw) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6b638e8aa45af063a73c2c8b5ccc0f12e0057f6b/frontend/src/components/form/SchoolNameField.tsx#L17)):*
> ```XML
>     <TextField
>       required
>       name='name'
> ```

Why was this renamed :thinking: 
___
*[`frontend/src/pages/teacherOnboarding/SchoolForm.tsx` line 46 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147#-NcYuPad4VpKvQnt97D7:-NcYuPad4VpKvQnt97D8:b-wz5rrl) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6b638e8aa45af063a73c2c8b5ccc0f12e0057f6b/frontend/src/pages/teacherOnboarding/SchoolForm.tsx#L46)):*
> ```XML
>               onSubmit();
>             })
>             .catch((err) => { console.log('CreateOrganisation submit error: ', err); });
> ```

I am not too sure if we already do this and this may be picky but for errors can we do console.error instead of log? Just to make it look like something went wrong in the console :)

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147)* status: 10 of 15 files reviewed, 5 unresolved discussions (waiting on @KamilPawel)

___
*[`frontend/src/app/api/endpoints/organisation.ts` line 27 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147#-NcYs8IC4UVmmbgLUhKf:-NcbBSjkCSY3SbsI-LIJ:b-8nlap4) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6b638e8aa45af063a73c2c8b5ccc0f12e0057f6b/frontend/src/app/api/endpoints/organisation.ts#L27)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Didn't we already add this to the default header?
</blockquote></details>

Not yet.
___
*[`frontend/src/app/api/endpoints/organisation.ts` line 42 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147#-NcYsB_k72QZuEsrDq-m:-NcbB_QbBhje4wH7kdw2:b-3cz4ey) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6b638e8aa45af063a73c2c8b5ccc0f12e0057f6b/frontend/src/app/api/endpoints/organisation.ts#L42)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Same here?
</blockquote></details>

Same above.
___
*[`frontend/src/components/form/SchoolNameField.tsx` line 17 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147#-NcYtYZE7peVReIVjt65:-NcbBmDL0ej4UYmQrtXC:b-mmfzcd) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6b638e8aa45af063a73c2c8b5ccc0f12e0057f6b/frontend/src/components/form/SchoolNameField.tsx#L17)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Why was this renamed :thinking:
</blockquote></details>

In the backend the value is retrieved with field "name". See `organisation_create` view.
___
*[`frontend/src/pages/teacherOnboarding/SchoolForm.tsx` line 46 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147#-NcYuPad4VpKvQnt97D7:-NcbCUBG7Jgunn5TBiRF:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6b638e8aa45af063a73c2c8b5ccc0f12e0057f6b/frontend/src/pages/teacherOnboarding/SchoolForm.tsx#L46)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

I am not too sure if we already do this and this may be picky but for errors can we do console.error instead of log? Just to make it look like something went wrong in the console :)
</blockquote></details>

Done.
___
*[`frontend/src/components/form/SchoolCountryField.tsx` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147#-NcYsO2WDqOFUGQv5WP0:-NcbBCqPAIBlbVcA0GcX:bmmo116) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6b638e8aa45af063a73c2c8b5ccc0f12e0057f6b/frontend/src/components/form/SchoolCountryField.tsx#L12)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Is this to prefill with dummy data?
</blockquote></details>

I was just trying out the [API](https://www.npmjs.com/package/country-list) :joy:

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147)* status: all files reviewed, 4 unresolved discussions (waiting on @cewei8483)

___
*[`frontend/src/components/form/SchoolNameField.tsx` line 17 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147#-NcYtYZE7peVReIVjt65:-NcbDxHMCRrd7A4DHBtK:by86fe3) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6b638e8aa45af063a73c2c8b5ccc0f12e0057f6b/frontend/src/components/form/SchoolNameField.tsx#L17)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

In the backend the value is retrieved with field "name". See `organisation_create` view.
</blockquote></details>

Can then we have matching names for the initial values? Formik has this thing where initial values keys will try to match to the name of the fields. So right now your requests have 3 fields that are not used :sweat_smile: 
___
*[`frontend/src/components/form/SchoolCountryField.tsx` line 12 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147#-NcYsO2WDqOFUGQv5WP0:-NcbEN8A6STxq-F-eREw:b-8erj5x) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/6b638e8aa45af063a73c2c8b5ccc0f12e0057f6b/frontend/src/components/form/SchoolCountryField.tsx#L12)):*
<details><summary><i>Previously, cewei8483 (Chi-En Wei) wrote…</i></summary><blockquote>

I was just trying out the [API](https://www.npmjs.com/package/country-list) :joy:
</blockquote></details>

:joy:

**Review by KamilPawel — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Pull request merged**
