### PR TITLE
feat: 19 api views

### PR DESCRIPTION
**Pull request by cewei8483**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/118)

### CODE REVIEW

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/118#-:-NaS6Hk17YuYhqbJjV-P:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/118)* status: all files reviewed, 1 unresolved discussion (waiting on @cewei8483)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/118#-NaS6YivCCc464mOKVet:-NaS6YivCCc464mOKVeu:bay6ggb) (no related file):*
Actually we might be missing some URLs?

___

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/118)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/118#-NaS6YivCCc464mOKVet:-NaSHY2yCwIeRRNKrM2o:b-896fix) (no related file):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I think we might be missing the URLs for `AnonymiseOrphanSchoolsView` and  `RemoveFakeAccounts`
</blockquote></details>

Done.

___

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/118)* status: all files reviewed, 1 unresolved discussion (waiting on @cewei8483)

___
*[`backend/portal/urls/api.py` line 17 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/118#-NaTmWqM5HryaTf8hxDS:-NaTmWqM5HryaTf8hxDT:b-xk8st) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/7993ebe90f536a46ce4000e2f5fae6177fefe7b5/backend/portal/urls/api.py#L17)):*
> ```Python
>         rf"^schools/anonymise/(?P<start_id>\d+)/$",
>         AnonymiseOrphanSchoolsView,
>         name="anonymise_orphan_schools-users",
> ```

just `anonymise_orphan_schools` is fine

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/118)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`backend/portal/urls/api.py` line 17 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/118#-NaTmWqM5HryaTf8hxDS:-NafG6Fb10L7WtsKK5jT:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/7993ebe90f536a46ce4000e2f5fae6177fefe7b5/backend/portal/urls/api.py#L17)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

just `anonymise_orphan_schools` is fine
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Pull request merged**
