### PR TITLE
feat: cypress plus codecov

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/2)

### CODE REVIEW

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/2)* status: 22 of 42 files reviewed, 3 unresolved discussions (waiting on @faucomte97)

*[a discussion](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/2#-NS6smwj-YOUe05t6rVe:-NSGt32e3m5hlyFtvGDB:b-896fix) (no related file):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Should we delete Cypress' default test files? Everything from `todo` to `window`? (I won't review these files yet)
</blockquote></details>

Done.

___
___
*[`cypress.config.ts` line 17 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/2#-NS6s3yD0BbrQwBWSv4n:-NSGt41r3qe__APcCUgw:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e55b7061f6b9a268ccff32d113b8bd38870b3f66/cypress.config.ts#L17)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Just checking, this should be updated by me once I add in the `run.py` commands right? Otherwise we'd have to run 3000 on top of the Django server
</blockquote></details>

Done.
___
*[`.github/workflows/main.yml` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/2#-NS6sWbsE2bC-AIeOVun:-NSGpd3p7qZ5Sq1clsyX:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/e55b7061f6b9a268ccff32d113b8bd38870b3f66/.github/workflows/main.yml#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

If this is a workflow for testing should we rename to something test-specific?
</blockquote></details>

Done.

**Review by SKairinos — COMMENTED** [review]
> Reviewed 42 of 42 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/2)* status: all files reviewed, 3 unresolved discussions (waiting on @faucomte97)

**Review by faucomte97 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
