### PR TITLE
fix: 99 new portal edit teacherdashboardclassesab123movestudentids=1

### PR DESCRIPTION
**Pull request by cewei8483**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/128)

### CODE REVIEW

**Comment by cewei8483** [comment]
Haven't reduced the padding but would like to fix the page loading issue first

**Comment by faucomte97** [comment]
@cewei8483 The page loading issue?

**Review by cewei8483 — COMMENTED** [review]
The dev page won't load for now: https://development-portal-dot-decent-digit-629.appspot.com/teacher/dashboard/classes/AB123/move/?studentIds=1,2,3

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/128#-:-Nb0gRpw1Rj-HZKeokDg:b-lyct7y)* status: 0 of 1 files reviewed, all discussions resolved

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/128)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @cewei8483)

___
*[`frontend/src/components/form/CflForm.tsx` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/128#-NbsNdYE99lm3SuXPiVB:-NbsNdYE99lm3SuXPiVC:b4lb606) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/1bde07e4ab09d9eb4812f2d7bd6627912ab10339/frontend/src/components/form/CflForm.tsx#L11)):*
> ```XML
> } from '@mui/material';
> import { Formik, FormikValues, FormikConfig, FormikProps, Form } from 'formik';
> import { theme } from 'codeforlife';
> ```

Are not using the useTheme hook anymore?

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/128)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[`frontend/src/components/form/CflForm.tsx` line 11 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/128#-NbsNdYE99lm3SuXPiVB:-NbsoXgB8VOdLHh0gZgf:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/1bde07e4ab09d9eb4812f2d7bd6627912ab10339/frontend/src/components/form/CflForm.tsx#L11)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

Are not using the useTheme hook anymore?
</blockquote></details>

Done.

**Review by KamilPawel — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Review by cewei8483 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cewei8483)

**Pull request merged**
