### PR TITLE
fix: update cfl js package version

### PR DESCRIPTION
**Pull request by cewei8483**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/148)

### CODE REVIEW

**Review by KamilPawel — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/148)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @cewei8483)

___
*[`frontend/package.json` line 75 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/148#-NcYwHV081gDr9z7l_zd:-NcYwHV081gDr9z7l_ze:b-d0wxhj) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/a861f68d140af4cfa68a1a4b5f7bce8ec1e25f09/frontend/package.json#L75)):*
> ```JSON
>     "exclude": []
>   }
> }
> ```

new line

**Review by cewei8483 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/148)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @KamilPawel)

___
*[`frontend/package.json` line 75 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/148#-NcYwHV081gDr9z7l_zd:-Ncb-azZ9N9EFdPpHLSJ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-portal-react/blob/a861f68d140af4cfa68a1a4b5f7bce8ec1e25f09/frontend/package.json#L75)):*
<details><summary><i>Previously, KamilPawel wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

**Review by KamilPawel — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/148)* status: all files reviewed, 1 unresolved discussion (waiting on @cewei8483)

**Review by KamilPawel — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-portal-react/148#-:-NcbDrhX9fWafo-PG5tH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @cewei8483)

**Pull request merged**
